import {test,expect} from '@playwright/test';
const reader=(page:any)=>page.locator('.physics-reading-modal');
test('기전력·각속도·진동수 기호는 그래프 축에서도 원식과 같은 기호로 읽힌다',async({page},info)=>{
 for(const [id,symbol] of [['c28-mutual-induction','ℰ'],['c9-precession','Ω']] as const){
  await page.goto(`/?space=demo&math=physics&physics=${id}&physicsSource=local#/math`);const d=page.locator('.physics-modal');await expect(d.locator('.ytitle')).toContainText(symbol);await expect(d.locator('.ytitle')).not.toContainText('mathcal');await expect(d.locator('.katex-error')).toHaveCount(0);
  if(id==='c28-mutual-induction')await page.screenshot({path:`work/physics-observations-20261003/${info.project.name}-axis-symbol-fixed.png`});
 }
});
test('연속 대조한 열·진동·소리 원식과 예외는 좁은 종이에서도 유지된다',async({page},info)=>{
 for(const id of ['7.3','9.3','10.5','11.1','12.5','13.2','14.2','15.6','16.4']){
  await page.goto(`/?space=demo&math=physics&physicsSection=${id}&physicsSource=local#/math`);const r=reader(page);await r.locator('.physics-verified-links summary').click();await expect(r.locator('.katex-error')).toHaveCount(0);expect(await r.evaluate(el=>el.scrollWidth<=el.clientWidth+2)).toBe(true);
  if(id==='12.5')await expect(r).toContainText('면적당 열저항');if(id==='13.2')await expect(r).toContainText('가열 조건을 붙여');if(id==='16.4')await expect(r).toContainText('두 번째 허용 모드');
 }await page.screenshot({path:`work/physics-observations-20261003/${info.project.name}-reviewed-source-paper.png`});
});
test('상호유도·로켓·맥놀이의 조건과 부호는 조절·재접속에서도 일치한다',async({page},info)=>{
 await page.goto('/?space=demo&math=physics&physics=c28-mutual-induction&physicsSource=local#/math');let d=page.locator('.physics-modal');await expect(d).toContainText('교재 밖 관찰 설계');await expect(d).toContainText('결합계수');const M=d.getByLabel('상호 인덕턴스 정확한 입력',{exact:true});await M.fill('0.1');await M.press('Enter');await d.getByLabel('일차 전류 변화율 정확한 입력',{exact:true}).fill('-10');await d.getByLabel('일차 전류 변화율 정확한 입력',{exact:true}).press('Enter');await expect(d.locator('[data-observation-region="readout"]')).toContainText('1');await page.reload();await expect(M).toHaveValue('0.1');await expect(d).toContainText('에너지 비음수 조건');await expect(d.locator('.katex-error')).toHaveCount(0);expect(await d.evaluate(el=>el.scrollWidth<=el.clientWidth+2)).toBe(true);await page.screenshot({path:`work/physics-observations-20261003/${info.project.name}-mutual-source-condition.png`});
 await page.goto('/?space=demo&math=physics&physics=c7-rocket&physicsSource=local#/math');d=page.locator('.physics-modal');await expect(d).toContainText('일정 분출 상대속력');const ratio=d.getByLabel('초기/최종 질량 정확한 입력',{exact:true});await ratio.fill('1');await ratio.press('Enter');await expect(d.locator('[data-observation-region="readout"]')).toContainText('0');await page.reload();await expect(ratio).toHaveValue('1');await expect(d.locator('.katex-error')).toHaveCount(0);
 await page.goto('/?space=demo&math=physics&physics=c16-beats&physicsSource=local#/math');d=page.locator('.physics-modal');const second=d.getByLabel('둘째 진동수 정확한 입력',{exact:true});await second.fill('5');await second.press('Enter');await expect(d).toContainText('원래 진동은 계속된다');await second.fill('10');await second.press('Enter');await expect(d).toContainText('설계 기준');await expect(d.locator('.katex-error')).toHaveCount(0);expect(await d.evaluate(el=>el.scrollWidth<=el.clientWidth+2)).toBe(true);
});
test('전자기파의 두 단위·시각 조절·원문 인쇄 오류는 실제 화면에서 구별된다',async({page},info)=>{
 await page.goto('/?space=demo&math=physics&physics=c27-em-plane-electric&physicsSource=local#/math');const d=page.locator('.physics-modal');await expect(d.getByRole('heading',{name:'같은 위치·시각의 자기장',exact:true})).toBeVisible();
 const position=d.getByLabel('관찰 위치 정확한 입력',{exact:true});await position.fill('0');await position.press('Enter');const time=d.getByLabel('주기 대비 시각 정확한 입력',{exact:true});await time.fill('1/2');await time.press('Enter');await expect(d.locator('[data-observation-region="readout"]')).toContainText('−20');await page.reload();await expect(position).toHaveValue('0');await expect(time).toHaveValue('1/2');await expect(d.locator('.katex-error')).toHaveCount(0);expect(await d.evaluate(el=>el.scrollWidth<=el.clientWidth+2)).toBe(true);
 await d.getByRole('button',{name:'연결된 원문 열기',exact:true}).click();await expect(page.locator('.physics-source-modal')).toContainText('PDF 954쪽');await page.locator('.physics-source-modal').getByRole('button',{name:'읽던 관찰로 돌아가기',exact:true}).click();await page.screenshot({path:`work/physics-observations-20261003/${info.project.name}-em-plane-wave.png`});
 for(const id of ['27.3','27.4','27.7']){await page.goto(`/?space=demo&math=physics&physicsSection=${id}&physicsSource=local#/math`);const r=reader(page);await r.locator('.physics-verified-links summary').click();await expect(r.locator('.katex-error')).toHaveCount(0);if(id==='27.7')await expect(r).toContainText('면적 미분 d가 빠져 있다');expect(await r.evaluate(el=>el.scrollWidth<=el.clientWidth+2)).toBe(true);}
});
test('제곱 항력과 일의 각도는 실제 조절·저장·원문·반대 부호로 연결된다',async({page},info)=>{
 for(const [id,pdf] of [['c5-drag-quadratic',128],['c6-constant-work',152]] as const){
  await page.goto(`/?space=demo&math=physics&physics=${id}&physicsSource=local#/math`);const d=page.locator('.physics-modal');await expect(d.locator('.katex-error')).toHaveCount(0);
  if(id==='c5-drag-quadratic'){await expect(d.getByRole('heading',{name:'같은 시각의 가속도',exact:true})).toBeVisible();const density=d.getByLabel('매질 밀도 정확한 입력',{exact:true});await density.fill('1.4');await density.press('Enter');await page.reload();await expect(density).toHaveValue('1.4');await expect(d).toContainText('부력과 다른 힘은 제외');}
  else {const angle=d.getByLabel('힘과 변위 사이각 정확한 입력',{exact:true});await angle.fill('pi');await angle.press('Enter');await expect(d.locator('[data-observation-region="readout"]')).toContainText('−10');await page.reload();await expect(angle).toHaveValue('pi');}
  expect(await d.evaluate(el=>el.scrollWidth<=el.clientWidth+2)).toBe(true);await d.getByRole('button',{name:'연결된 원문 열기',exact:true}).click();await expect(page.locator('.physics-source-modal')).toContainText(`PDF ${pdf}쪽`);await page.locator('.physics-source-modal').getByRole('button',{name:'읽던 관찰로 돌아가기',exact:true}).click();await page.screenshot({path:`work/physics-observations-20261003/${info.project.name}-${id}-conditions.png`});
 }
});
test('새로 대조한 역학의 긴 원식·계·예외 해설은 종이 면에서 읽힌다',async({page})=>{
 for(const id of ['3.4','4.2','5.2','6.4','6.6']){await page.goto(`/?space=demo&math=physics&physicsSection=${id}&physicsSource=local#/math`);const r=reader(page);await r.locator('.physics-verified-links summary').click();await expect(r.locator('.katex-error')).toHaveCount(0);expect(await r.evaluate(el=>el.scrollWidth<=el.clientWidth+2)).toBe(true);if(id==='6.4')await expect(r).toContainText('모든 두 경로의 일이 반드시 다르다는 뜻이 아니라');}
});
test('속도·가속도 부호 관찰은 서로 다른 축·조건·입력·원문을 복원한다',async({page},info)=>{
 await page.goto('/?space=demo&math=physics&physics=c3-kinematic-velocity&physicsSource=local#/math');const d=page.locator('.physics-modal');
 await expect(d).toContainText('현재 속력이 감소한다');await expect(d.getByRole('heading',{name:'같은 시각의 가속도',exact:true})).toBeVisible();
 const a=d.getByLabel('초기 가속도 정확한 입력',{exact:true});await a.fill('-2');await a.press('Enter');await expect(d).toContainText('현재 속력이 증가한다');
 await d.getByLabel('이 기기의 관찰 메모',{exact:true}).fill('음의 속도·음의 가속도 → 속력 증가');await page.reload();await expect(a).toHaveValue('-2');await expect(d).toContainText('현재 속력이 증가한다');
 await expect(d.getByLabel('이 기기의 관찰 메모',{exact:true})).toHaveValue('음의 속도·음의 가속도 → 속력 증가');await expect(d.locator('.katex-error')).toHaveCount(0);expect(await d.evaluate(el=>el.scrollWidth<=el.clientWidth+2)).toBe(true);
 await d.getByRole('button',{name:'연결된 원문 열기',exact:true}).click();await expect(page.locator('.physics-source-modal')).toContainText('PDF 61쪽');await page.locator('.physics-source-modal').getByRole('button',{name:'읽던 관찰로 돌아가기',exact:true}).click();await page.screenshot({path:`work/physics-observations-20261003/${info.project.name}-velocity-sign.png`});
});
test('원본 그림·쪽번호·보기 선택·메모를 복원하고 렌더 실패에서 다시 읽는다',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/?space=demo&math=physics&physicsSection=17.6&physicsSource=local#/math');const r=reader(page);await r.getByLabel('이 절 원문 PDF 페이지',{exact:true}).selectOption('598');await r.getByLabel('이 절의 조건·관계 메모',{exact:true}).fill('책588 / PDF598 · i의 부호');await r.getByRole('button',{name:'원본 그림·수식 펼치기',exact:true}).click();const img=r.locator('.physics-original-page');await expect(img).toBeVisible();await expect.poll(()=>img.evaluate((el:HTMLImageElement)=>el.naturalWidth)).toBeGreaterThan(1000);await page.reload();await expect(r.getByLabel('이 절 원문 PDF 페이지',{exact:true})).toHaveValue('598');await expect(r.getByLabel('이 절의 조건·관계 메모',{exact:true})).toHaveValue('책588 / PDF598 · i의 부호');await expect(img).toBeVisible();await page.route('**/__physics/image/**',route=>route.fulfill({status:503,body:'render failed'}));await r.getByRole('button',{name:'이 절의 뒤쪽',exact:true}).click();await expect(r.getByText('원본 페이지를 그리지 못했다. 쪽 위치와 메모는 유지했다.',{exact:true})).toBeVisible();await expect(r.getByLabel('이 절의 조건·관계 메모',{exact:true})).toHaveValue('책588 / PDF598 · i의 부호');await page.unroute('**/__physics/image/**');await r.getByRole('button',{name:'원본 페이지 다시 불러오기',exact:true}).click();await expect(img).toBeVisible();await expect.poll(()=>img.evaluate((el:HTMLImageElement)=>el.naturalWidth)).toBeGreaterThan(1000);await r.getByRole('button',{name:'본문 추출본 읽기',exact:true}).click();await expect(r.locator('pre')).not.toBeEmpty();await expect(r.locator('.katex-error')).toHaveCount(0);expect(await r.evaluate(el=>el.scrollWidth<=el.clientWidth+2)).toBe(true);await page.screenshot({path:`work/physics-observations-20261003/${info.project.name}-complete-source.png`});expect(errors).toEqual([]);
});
test('벡터·광선·위상 도해가 조절·복원과 같은 조건을 공유한다',async({page},info)=>{
 for(const id of ['c2-vector-sum','c17-snell','c17-lens','c28-rlc']){
  await page.goto(`/?space=demo&math=physics&physics=${id}&physicsSource=local#/math`);const d=page.locator('.physics-modal').filter({has:page.locator('.physics-spatial')});await expect(d.locator('.physics-spatial svg')).toBeVisible();await expect(d.locator('.katex-error')).toHaveCount(0);expect(await d.evaluate(el=>el.scrollWidth<=el.clientWidth+2)).toBe(true);
  if(id==='c2-vector-sum'){const angle=d.getByLabel('방향각 정확한 입력',{exact:true});await angle.fill('pi/2');await angle.press('Enter');await expect(d.locator('.physics-spatial tr').filter({hasText:'합의 y 성분'})).toContainText('3.00000');await page.reload();await expect(page.getByLabel('방향각 정확한 입력',{exact:true})).toHaveValue('pi/2');await page.screenshot({path:`work/physics-observations-20261003/${info.project.name}-complete-vector.png`});}
 }
});
test('대조한 원문 관계는 실제 책 쪽·PDF 쪽·관찰과 함께 열린다',async({page})=>{
 await page.goto('/?space=demo&math=physics&physicsSection=26.1&physicsSource=local#/math');const r=reader(page);await r.locator('.physics-verified-links summary').click();await expect(r.locator('.physics-verified-links')).toContainText('Eq26.6은 긴 도선 식');await r.getByRole('button',{name:'책 891쪽 · PDF 897쪽 원본 열기',exact:true}).first().click();await expect(r.getByLabel('이 절 원문 PDF 페이지',{exact:true})).toHaveValue('897');await expect(r.locator('.physics-original-page')).toBeVisible();await r.getByRole('button',{name:'대응 관찰 · 유한 직선 도선의 자기장',exact:true}).click();const d=page.locator('.physics-modal');await expect(d.locator('.katex-error')).toHaveCount(0);await d.getByRole('button',{name:'연결된 원문 열기',exact:true}).click();await expect(page.locator('.physics-source-modal')).toContainText('책 891쪽 · PDF 897쪽');await page.locator('.physics-source-modal').getByRole('button',{name:'읽던 관찰로 돌아가기',exact:true}).click();await d.getByRole('button',{name:'읽던 원문 관찰로 돌아가기',exact:true}).click();await expect(r.getByLabel('이 절 원문 PDF 페이지',{exact:true})).toHaveValue('897');await expect(r.locator('.physics-original-page')).toBeVisible();
});

test('정의·틀린 식·벡터 성질의 긴 원문 연결 수식은 종이 안에서 읽힌다',async({page})=>{for(const id of ['1.1','1.2','1.3','2.2','2.3','2.4']){await page.goto(`/?space=demo&math=physics&physicsSection=${id}&physicsSource=local#/math`);const r=reader(page);await r.locator('.physics-verified-links summary').click();await expect(r.locator('.katex-error')).toHaveCount(0);if(id==='1.3'){await expect(r.locator('.physics-verified-links')).toContainText('원문이 일부러 제시한 틀린 식');}if(id==='2.4'){await expect(r.locator('.physics-verified-links')).toContainText('교재 밖 검토 설명');}expect(await r.evaluate(el=>el.scrollWidth<=el.clientWidth+2)).toBe(true);}});

test('세부 식에서 작업대로 펼쳐도 그 식의 출처와 실제 호출 절로 복귀한다',async({page})=>{await page.goto('/?space=demo&physicsSection=2.4&physicsSource=local#/materials/physics-principles');let r=reader(page);await r.locator('.physics-verified-links summary').click();const link=r.locator('.physics-verified-links > section').filter({hasText:'2.37 ·'});await link.getByRole('button',{name:'책 31쪽 · PDF 48쪽 원본 열기',exact:true}).click();await link.getByRole('button',{name:'대응 관찰 · 벡터의 곱',exact:true}).click();let d=page.locator('.physics-modal').filter({has:page.locator('[data-observation-region="readout"]')});await d.getByRole('button',{name:'탐구 작업대에서 전체 관찰 열기',exact:true}).click();await expect(page).toHaveURL(/physicsSourcePage=48/);d=page.locator('.physics-modal').filter({has:page.locator('[data-observation-region="readout"]')});await d.getByRole('button',{name:'연결된 원문 열기',exact:true}).click();await expect(page.locator('.physics-source-modal')).toContainText('책 31쪽 · PDF 48쪽');await page.locator('.physics-source-modal').getByRole('button',{name:'읽던 관찰로 돌아가기',exact:true}).click();await d.getByRole('button',{name:'읽던 원문 관찰로 돌아가기',exact:true}).click();r=reader(page);await expect(r.getByLabel('이 절 원문 PDF 페이지',{exact:true})).toHaveValue('48');await r.getByRole('button',{name:'읽던 절로 돌아가기',exact:true}).click();await expect(page).toHaveURL(/physicsReading=2.4/);await expect(page.locator('#physics-section-2\\.4 button').first()).toBeFocused();});

test('개수 분포와 확률밀도·원문 구름 기호는 실제 화면과 출처에 일치한다',async({page},info)=>{
 for(const [id,pdf] of [['c13-maxwell',453],['c8-rolling',272]] as const){
  await page.goto(`/?space=demo&math=physics&physics=${id}&physicsSource=local#/math`);const d=page.locator('.physics-modal');await expect(d.locator('.katex-error')).toHaveCount(0);
  if(id==='c13-maxwell'){await expect(d).toContainText('속력별 개수 밀도');await expect(d).toContainText('정규화 확률밀도');}
  else {const input=d.getByLabel('질량분포 비율 정확한 입력',{exact:true});await input.fill('0.6');await input.press('Enter');await page.reload();await expect(d.getByLabel('질량분포 비율 정확한 입력',{exact:true})).toHaveValue('0.6');await expect(d.locator('.physics-number').filter({hasText:'질량분포 비율'})).toContainText('β');}
  expect(await d.evaluate(el=>el.scrollWidth<=el.clientWidth+2)).toBe(true);await page.screenshot({path:`work/physics-observations-20261003/${info.project.name}-${id}-source-symbols.png`});await d.getByRole('button',{name:'연결된 원문 열기',exact:true}).click();await expect(page.locator('.physics-source-modal')).toContainText(`PDF ${pdf}쪽`);await page.locator('.physics-source-modal').getByRole('button',{name:'읽던 관찰로 돌아가기',exact:true}).click();await d.getByRole('button',{name:'교재 관찰 목록으로',exact:true}).click();await expect(d).toHaveCount(0);await expect(page.getByRole('heading',{name:'물리 교재 관찰',exact:true})).toBeVisible();
 }
});

test('새 전체 읽기의 광학·전기 원식과 적용 조건이 실제 종이에서 읽힌다',async({page},info)=>{
 for(const [id,phrase] of [['17.6','근축'],['18.5','m=0'],['20.4','전하'],['21.4','공동'],['22.13','편미분'],['23.3','유전체'],['24.7','충전']] as const){
  await page.goto(`/?space=demo&math=physics&physicsSection=${id}&physicsSource=local#/math`);const r=reader(page);await r.locator('.physics-verified-links summary').click();await expect(r.locator('.physics-verified-links')).toContainText(phrase);await expect(r.locator('.katex-error')).toHaveCount(0);expect(await r.evaluate(el=>el.scrollWidth<=el.clientWidth+2)).toBe(true);
  if(id==='23.3')await page.screenshot({path:`work/physics-observations-20261003/${info.project.name}-final-dielectric-paper.png`});
 }
});
test('자기 원식의 조건·스핀 오기와 빛의 축 기호는 실제 화면에 유지된다',async({page},info)=>{
 for(const [id,phrase] of [['25.1','자기력'],['26.1','Eq26.6은 긴 도선 식'],['26.3','순전류0'],['26.6','계수2'],['26.8','온도에 거의 독립적']] as const){
  await page.goto(`/?space=demo&math=physics&physicsSection=${id}&physicsSource=local#/math`);const r=reader(page);await r.locator('.physics-verified-links summary').click();await expect(r.locator('.physics-verified-links')).toContainText(phrase);await expect(r.locator('.katex-error')).toHaveCount(0);expect(await r.evaluate(el=>el.scrollWidth<=el.clientWidth+2)).toBe(true);
 }
 await page.goto('/?space=demo&math=physics&physics=c18-slits&physicsSource=local#/math');const d=page.locator('.physics-modal');await expect(d.locator('.xtitle')).toContainText('y');await expect(d.locator('.ytitle')).toContainText('I/I');await expect(d.locator('.katex-error')).toHaveCount(0);expect(await d.evaluate(el=>el.scrollWidth<=el.clientWidth+2)).toBe(true);await page.screenshot({path:`work/physics-observations-20261003/${info.project.name}-final-slit-paper.png`});
});
test('부록은 기존 책장에서 실제 원문으로 열고 같은 과업으로 돌아온다',async({page},info)=>{
 await page.goto('/?space=demo&math=physics&physicsSource=local#/math');await page.getByText('부록과 색인에서 관계 확인',{exact:true}).click();const opener=page.getByRole('button',{name:'부록 A · 단위 환산 원문 열기',exact:true});await opener.click();const s=page.locator('.physics-source-modal');await expect(s).toContainText('PDF 1004쪽');await expect(s.locator('pre')).toContainText('Conversion Factors');await s.getByRole('button',{name:'읽던 관찰로 돌아가기',exact:true}).click();await expect(opener).toBeFocused();await expect(page.locator('.physics-book')).toContainText('같은 물리량끼리 환산');expect(await page.locator('.physics-book').evaluate(el=>el.scrollWidth<=el.clientWidth+2)).toBe(true);await page.screenshot({path:`work/physics-observations-20261003/${info.project.name}-final-supplementary.png`});
});

test('세기 설명의 아래첨자는 소리·슬릿·박막에서 실제 수식으로 읽힌다',async({page},info)=>{
 for(const id of ['c15-sound','c18-slits','c18-thin-film']){
  await page.goto(`/?space=demo&math=physics&physics=${id}&physicsSource=local#/math`);const d=page.locator('.physics-modal');await expect(d.locator('.katex-error')).toHaveCount(0);const condition=d.locator('[data-observation-region="question"] > .physics-prose');expect(await condition.evaluate(el=>el.innerText)).not.toContain('I_');expect(await condition.locator('.katex').count()).toBeGreaterThan(0);expect(await d.evaluate(el=>el.scrollWidth<=el.clientWidth+2)).toBe(true);
  if(id==='c18-slits')await page.screenshot({path:`work/physics-observations-20261003/${info.project.name}-final-inline-math.png`});
 }
});
