import {expect,it} from 'vitest';
import {createDemoState} from './fixtures';
import {emptyRecommendations,nextStudy,recommendationInput,validateRecommendations,makeResultEvent,emptyResponse} from './recommendation-workspace';
import type {LearningSchedule} from './learning-schedule';
const now='2026-10-01T01:00:00Z',t='demo-topic-function',p='demo-topic-graph',subjectId='demo-subject-math';
function setup(){const data=createDemoState(),w=emptyRecommendations(data);w.goals=[{id:'g',targetId:t,label:'조건 설명',dueDate:'',novelty:'new',createdAt:now,ended:false},{id:'p',targetId:p,label:'선행 설명',dueDate:'',novelty:'same',createdAt:now,ended:false}];return{data,w};}
const schedule:LearningSchedule={id:'schedule',subjectId,name:'실제 시험',kind:'exam',goalIds:[],targetIds:[t],dueDate:'2026-10-02',opensDate:'2026-10-01',weight:.5,status:'active',states:{},dueMeaning:'exam',note:'원문\n예외'};
it('uses actual assessment weight, exact Korean opening and explicit prerequisites without deriving them from the outline',()=>{const{data,w}=setup();w.schedules=[schedule];expect(recommendationInput(data,w).model.targets[0].prerequisites).toEqual([]);w.conditions=[{targetId:t,prerequisiteIds:[p],materialAvailable:true}];validateRecommendations(w,data);const input=recommendationInput(data,w);expect(input.model.assessments.at(-1)).toMatchObject({weight:.5,opensAt:'2026-09-30T15:00:00.000Z'});expect(nextStudy(data,w,now).cards[0].targetId).toBe(p);w.conditions.push({targetId:p,prerequisiteIds:[t],materialAvailable:null});expect(()=>validateRecommendations(w,data)).toThrow('순환');});
it('separates preparation/submission and watching/learning/attendance and respects deadline meanings',()=>{const{data,w}=setup();w.schedules=[{...schedule,kind:'assignment',dueMeaning:'submission',states:{prepare:'done',submit:'unknown'}},{...schedule,id:'lecture',kind:'lecture',dueMeaning:'attendance',states:{watch:'done',learn:'unknown',attendance:'not-done'}}];const tasks=recommendationInput(data,w).model.tasks;expect(tasks.find(x=>x.kind==='prepare')!.status).toBe('ended');expect(tasks.find(x=>x.kind==='submit')!.status).toBe('active');expect(tasks.find(x=>x.kind==='watch')!.status).toBe('ended');expect(tasks.find(x=>x.kind==='learn')!.dueAt).toBeNull();expect(tasks.find(x=>x.kind==='attendance')!.dueAt).not.toBeNull();expect(nextStudy(data,w,now).cards.some(c=>c.action==='submit')).toBe(true);});
it('does not satisfy delayed transfer from same-item, unknown delay or early confirmation',()=>{const{data,w}=setup();w.goals[0].minDelayDays=7;for(const response of [{...emptyResponse(),result:'pass' as const,novelty:'new' as const,assistance:'none' as const},{...emptyResponse(),result:'pass' as const,novelty:'same' as const,assistance:'none' as const,delayDays:10,delayVerified:true},{...emptyResponse(),result:'pass' as const,novelty:'new' as const,assistance:'none' as const,delayDays:2,delayVerified:true}]){w.events=[makeResultEvent(w.goals[0],response,w,now,'e')];expect(nextStudy(data,w,now).states.g.status).not.toBe('confirmed');}w.events=[makeResultEvent(w.goals[0],{...emptyResponse(),result:'pass',novelty:'new',assistance:'none',delayDays:7,delayVerified:true},w,now,'e')];expect(nextStudy(data,w,now).states.g.status).toBe('confirmed');});
it('only offers a personalised method for sufficient independent preregistered pairs with separated bounds',()=>{const{data,w}=setup();w.comparisons=Array.from({length:16},(_,i)=>({id:`pair${i}`,targetId:t,goalId:'g',action:i<8?'설명 인출':'읽기',registeredAt:'2026-09-01T00:00:00Z',before:.1,after:i<8?.9:.1,outcomeDueAt:'2026-09-30T00:00:00Z',independent:true,rubricMatched:true,attributionBundle:true,performed:true,note:'가상 검산'}));expect(nextStudy(data,w,now).adaptations?.[0].action).toBe('설명 인출');w.comparisons[0].independent=false;expect(nextStudy(data,w,now).adaptations).toEqual([]);w.comparisons.forEach(x=>{x.independent=true;x.after=null;});expect(nextStudy(data,w,now).adaptations).toEqual([]);});
