import type { AdvancedKind } from './linear-algebra-advanced';
import type { ObservationSpec } from './linear-algebra-specs';
const spec=(question:string,matrix:string,conditions:string[],roles:string[],extra:Partial<ObservationSpec>={}):ObservationSpec=>({question,matrix,conditions,representations:roles,initialReason:'설명용 초기값에서 주요 관계가 드러나도록 골랐다. 원문 문제나 실제 관측값으로 저장하지 않는다.',limitations:['작은 유한차원 수치 예제이다. 일반 정리·정확한 기호 판정·증명은 원문 조건과 구별한다.'],...extra});
export const ADVANCED_SPECS:Record<AdvancedKind,ObservationSpec>={
  'weighted-qr':spec('내적을 바꾸면 같은 독립 열의 직교화는 어떻게 달라지는가?','1 1\n0 1',['독립인 열 A · 같은 행 차원의 대칭 양정치 G','QᵀGQ=I · 유클리드 직교와 구별'],['A의 열: 순서 있는 방향','G: 측정 규칙','Q,R: 직교 기저와 같은 생성공간'],{auxiliary:{label:'내적 행렬 G · 대칭 양정치',value:'1 0\n0 1'}}),
  geometry:spec('같은 벡터와 도형은 2·3차원 행렬 작용에서 어떻게 대응하는가?','1 0 0\n0 1 0\n0 0 1',['2×2 또는3×3 실수 행렬과 같은 차원의 벡터','축 회전은3차원 · 오른손 좌표계의 능동 회전'],['원도형과 상: 대응 모서리','입력 벡터와 상: 동일 대상','직교 잔차: 길이 보존 조건'],{auxiliary:{label:'입력 벡터 x · 한 열',value:'1\n1\n1'},t:{label:'축 회전 각도 · 라디안',min:-Math.PI,max:Math.PI,value:Math.PI/4},modes:[{value:'matrix',label:'입력 행렬의 작용'},{value:'x',label:'x축 회전'},{value:'y',label:'y축 회전'},{value:'z',label:'z축 회전'}],isSpatial:true}),
  objects:spec('다항식·행렬과 좌표 열은 어떤 기저 순서로 대응하는가?','1 2 3',['다항식은 낮은 차수부터 한 행','행렬은 행 우선 순서의 위치별 표준기저','동형만으로 내적 보존을 가정하지 않는다.'],['원래 대상: 다항식·행렬','좌표 열: 선택한 표준기저','미분: 계수의 이동과 배율'],{modes:[{value:'polynomial',label:'다항식과 미분'},{value:'matrix',label:'행렬과 성분 좌표'}],axis:['독립변수','함숫값']}),
  fourier:spec('다항식의 적분 계수와 유한 푸리에 근사는 어떻게 대응하는가?','0 1',['[0,2π] 적분 내적 · 한 행의 다항식 계수','유한 차수0~15 · 끝점의 주기 연장 구별'],['다항식: 원함수','aₙ,bₙ: 직교 성분의 계수','부분합·적분 오차: 유한 최선근사'],{n:{label:'푸리에 차수',min:0,max:15,value:4},axis:['독립변수 x · 라디안','함숫값']}),
  power:spec('같은 초기 벡터의 정규화 규칙과 반복 횟수는 무엇을 바꾸는가?','2 1\n1 2',['실수 대칭 정사각행렬 · 비영 초기 벡터','양의 지배값의 엄격한 절댓값 우위와 비영 초기 성분은 별도 확인'],['초기·현재 방향: 반복 상태','레일리 몫: 고유값 추정','잔차·추정값 변화: 서로 다른 근거'],{auxiliary:{label:'초기 벡터 x₀ · 한 열',value:'1\n0'},n:{label:'반복 횟수',min:0,max:30,value:5},modes:[{value:'euclidean',label:'유클리드 노름 정규화'},{value:'maximum',label:'최대 절댓값 성분 정규화'}],isSpatial:true}),
  representation:spec('입력·출력 기저를 바꾸면 같은 선형 작용의 표현행렬은 어떻게 달라지는가?','1 2\n0 1',['입력 기저 B는 정의역, 출력 기저 C는 공역의 가역 기저','각 기저 벡터를 열로 넣는다.','같은 공간에서 B=C일 때 닮음 B⁻¹AB'],['A: 원래 작용','C⁻¹AB: 선택한 기저의 표현','재구성: 같은 작용의 보존'],{auxiliary:{label:'입력 기저 B와 출력 기저 C · ---로 분리',value:'1 1\n0 1\n---\n1 1\n0 1'}}),
  elementary:spec('행 연산의 누적 기본행렬은 원래 확대행렬과 어떻게 대응하는가?','1 1 3\n2 -1 0',['마지막 열이 b인 확대행렬','각 행 연산을 항등행렬에도 같은 순서로 적용한다.'],['확대행렬: 같은 해집합','단계: 순서와 근거','E[A|b]: 누적 행 연산의 재구성']),
  cofactor:spec('여인수·수반행렬·크래머 분자는 같은 가역 조건에서 어떻게 연결되는가?','2 1 5\n1 3 7',['n행 n+1열의 실수 확대행렬','역행렬과 크래머 공식은 det A≠0에서만 적용'],['여인수 행렬: 부호와 소행렬','전개 항: 행렬식의 합','역행렬·크래머 해: 같은 해의 비교']),
  spaces:spec('행·열·영·왼쪽 영공간의 기저와 차원은 어떤 직교 대응을 가지는가?','1 1 0\n0 1 1\n1 2 1',['실수 m×n 행렬','열공간 기저는 원래 행렬의 피벗 열','공역은 Rᵐ으로 명시한다.'],['원래 열과 RREF행: 기저의 선택','자유변수 벡터: 영공간','차원·직교 잔차: 네 공간의 관계'],{isSpatial:true}),
  coordinates:spec('벡터를 고정한 채 기저를 바꾸면 좌표는 어떻게 바뀌고 다시 같은 벡터가 되는가?','1 1\n0 1',['B,C는 가역인 같은 n×n 기저 행렬','x는 n×1 고정 벡터','입력 기저의 벡터를 행렬의 열로 넣는다.'],['기저 벡터: 같은 공간의 방향','좌표 열: 선택한 기저의 계수','C⁻¹B: 좌표 사이의 전이'],{auxiliary:{label:'기저 C와 고정 벡터 x · ---로 분리',value:'1 0\n0 1\n---\n3\n2'},isSpatial:true}),
  composition:spec('먼저와 나중의 변환은 AB와 BA에 어떻게 다르게 대응하는가?','1 1\n0 1',['곱의 안쪽 차원 조건','T_A∘T_B는 먼저 B, 다음 A'],['행렬 A,B: 두 작용','ABx·BAx: 순서의 차이','x와 중간 상: 동일 대상의 과정'],{auxiliary:{label:'행렬 B · 행마다 줄바꿈',value:'0 -1\n1 0'},isSpatial:true}),
  'matrix-operations':spec('두 행렬의 덧셈·스칼라배·전치·곱에는 각각 어떤 크기 조건이 필요한가?','1 2\n0 1',['덧셈은 같은 크기','곱은 안쪽 차원이 같을 때 정의','정수 거듭제곱은 정사각행렬; 음의 지수는 가역 조건'],['A,B: 두 대상','A+B,tA,Aᵀ: 대응 성분','AB,BA: 곱의 순서와 크기','Aⁿ: 반복 곱과 역의 조건'],{auxiliary:{label:'행렬 B · 행마다 줄바꿈',value:'0 1\n2 0'},t:{label:'스칼라 배율',min:-5,max:5,value:2},n:{label:'정수 거듭제곱',min:-5,max:5,value:2}}),
  affine:spec('동차좌표에서 평행이동을 포함한 행렬은 R²의 선형변환과 무엇이 다른가?','0 -1 2\n1 0 1\n0 0 1',['마지막 행이 [0,0,1]인 실수3×3','평면 좌표 [x,y,1]','평행이동은 R²의 원점을 보존하지 않는다.'],['2×2블록: 선형 작용','마지막 열: 평행이동','원도형·상: 같은 꼭짓점의 대응'],{t:{label:'입력 벡터의 두 번째 성분',min:-5,max:5,value:1},isSpatial:true}),
  'weighted-inner':spec('측정 규칙 G를 바꾸면 내적·노름·각도와 직교 판단은 어떻게 변하는가?','2 1\n1 2',['G는 실수 대칭 양정치','u,v는 G와 같은 차원','0벡터와의 각도는 정의하지 않는다.'],['G: 내적의 측정 규칙','내적·노름·각도: 같은 벡터의 측정','정사영 잔차: 선택한 내적에서의 직교'],{auxiliary:{label:'벡터 u와 v · 각 벡터를 한 행에',value:'1 0\n1 1'},isSpatial:true}),
  'subspace-projection':spec('종속인 생성집합도 같은 유일한 정사영을 주며 계수에는 어떤 자유도를 남기는가?','1 2\n1 2\n0 0',['실수 유클리드 내적','A의 열이 생성하는 부분공간','종속 열도 허용; b는 한 열'],['Q·P_W: 부분공간과 정사영','b,p,r: 벡터의 분해','x₀+Null(A): 최소제곱 계수의 해집합'],{auxiliary:{label:'벡터 b · 한 열로 입력',value:'1\n2\n3'},isSpatial:true}),
  'complex-matrix':spec('켤레전치와 두 곱의 순서는 에르미트·유니터리·정규를 어떻게 구별하는가?','1 i\n-i 2',['복소 성분 예: 1+2i · 최대6×6','세 행렬 조건은 정사각행렬에서 판단','복소 내적은 첫 인자에 선형인 교재 관례'],['A와 A*: 성분의 켤레·전치','A*A와 AA*: 순서의 대응','조건별 잔차: 서로 다른 행렬 성질']),
  triangular:spec('헤센베르크와 실수 상삼각 슈어 형태는 어떤 조건과 제거 영역이 다른가?','1 2 3\n4 5 6\n7 8 10',['헤센베르크: 일반 실수 정사각행렬','실수 상삼각 슈어: 실수 고유값 조건','H의 대각 성분을 일반적으로 고유값으로 읽지 않는다.'],['직교 P: 기저의 변화','H 또는 S: 제거되는 영역','분해 단계·재구성: 같은 작용의 보존'],{modes:[{value:'hessenberg',label:'헤센베르크 변환'},{value:'schur',label:'실수 상삼각 슈어 분해'}]}),
  spectral:spec('대칭행렬의 같은 고유쌍은 정사영별 재구성과 단위구면의 극값에 어떻게 다시 쓰이는가?','2 1 0\n1 2 0\n0 0 4',['실수 대칭 n×n','단위구면의 극값과 일반 함수의 임계점은 구별','반정치 헤시안만으로 국소 극값을 확정하지 않는다.'],['Q,D: 정규직교 고유기저','λᵢuᵢuᵢᵀ: 투영과 배율','최대·최소 고유값: 단위구면의 극값']),
  'eigen-general':spec('고유벡터의 열 순서와 고유값의 순서를 맞추면 P⁻¹AP=D가 어떻게 재구성되는가?','2 1 0\n0 1 0\n0 0 3',['실수 정사각 입력; 결과의 실수·복소수를 구별','비영 독립 고유벡터가 n개 필요','반복 고유값만으로 대각화 여부를 확정하지 않는다.'],['고유쌍: 방향과 배율','P: 고유벡터를 열로 배열','D·P⁻¹AP: 같은 작용의 좌표 표현']),
  ldu:spec('교환·소거·대각 배율을 분리한 한 분해로 여러 오른쪽 벡터를 어떻게 다시 푸는가?','0 2\n1 3',['실수 가역 정사각행렬의 수치 분해','PA=LDU₁ · U₁ 대각은1','B의 각 열은 별도 오른쪽 벡터'],['P,L,D,U₁: 연산의 역할','전진·후진 대입: 분해 재사용','AX−B: 여러 해의 재구성'],{auxiliary:{label:'복수 오른쪽 벡터 B · 행마다 줄바꿈',value:'4 2\n7 4'}}),
  'data-fit':spec('자료·모형 열·계수·잔차는 선택한 다항식 모형에 어떻게 대응하는가?','1 1\n2 2\n3 2\n4 4',['각 행이 x,y 표본쌍','다항식 차수0~4 · 유한 표본만 적합','초기 표본은 설명용; 실제 단위·관측 여부는 추정하지 않는다.'],['표본: 입력 자료','모형 열: 1,x,…','잔차와 정규방정식: 적합 관계'],{modes:[{value:'polynomial',label:'다항식 모형'},{value:'logarithmic',label:'로그 모형 · x>0'}],n:{label:'다항식 차수',min:0,max:4,value:1},axis:['입력 x · 사용자가 정한 단위','자료 y · 사용자가 정한 단위']}),
  'function-inner':spec('다항식의 적분 내적은 함수의 길이·거리·직교화와 최선근사를 어떻게 측정하는가?','0 1 0\n1 0 1',['각 행은 낮은 차수부터의 다항식 계수 · 비교 방식은 두 행','구간[−1,1]의 적분 내적 · 직교화에는 독립 조건','최선근사는 첫 행의 함수를 차수 n 이하 공간에 투영'],['계수와 함수곡선: 같은 대상','해석적 적분: 내적·노름·거리','직교화·정사영: 함수 공간의 관계'],{n:{label:'최선근사 다항식 차수',min:0,max:5,value:2},modes:[{value:'pair',label:'두 함수의 내적·정사영'},{value:'basis',label:'함수들의 직교화'},{value:'best',label:'첫 함수의 최선근사'}],axis:['독립변수','함숫값']}),
  'matrix-dynamics':spec('같은 A와 초기 상태에서 이산 Aᵏ과 연속 eᵗᴬ는 어떻게 다른 변화를 만드는가?','0 1\n-1 0',['실수 정사각행렬','초기 상태는 같은 차원의 한 열','이산 단계와 연속 시간은 별도 축'],['이산 상태: A를 반복 적용','연속 상태: 행렬지수 해','초기 상태·성분: 두 표현의 동일 대상'],{auxiliary:{label:'초기 상태 x₀ · 한 열로 입력',value:'1\n0'},t:{label:'연속 관찰 종료 시간',min:0,max:5,value:2},n:{label:'이산 반복 횟수',min:0,max:20,value:5},axis:['이산 단계','상태 성분']}),
};

Object.assign(ADVANCED_SPECS.elementary, {matrixLabel:'확대행렬 [A | b] · 마지막 열이 b'});
Object.assign(ADVANCED_SPECS.cofactor, {matrixLabel:'확대행렬 [A | b] · n행 n+1열'});
Object.assign(ADVANCED_SPECS.coordinates, {matrixLabel:'기저 B · 기저 벡터를 열에 넣기'});
Object.assign(ADVANCED_SPECS['weighted-inner'], {matrixLabel:'내적 규칙 G · 실수 대칭 양정치'});
Object.assign(ADVANCED_SPECS['data-fit'], {matrixLabel:'자료 표본 · 각 행에 x y'});
Object.assign(ADVANCED_SPECS['function-inner'], {matrixLabel:'함수 f,g의 다항식 계수 · 낮은 차수부터 각 행에'});
Object.assign(ADVANCED_SPECS['complex-matrix'], {matrixLabel:'복소 행렬 A · 성분 예: 1+2i'});
