import type { PhysicsObservation, PhysicsValues } from './physics-observations';
const extraKe=8.9875517923e9,extraEpsilon=8.8541878128e-12,extraMu=4*Math.PI*1e-7;
/** Explicit formula cases; source and user input are never executed as code. */
export function additionalPhysics(item:PhysicsObservation,p:PhysicsValues,x:number):number|null {
  let y:number;
  switch(item.engine) {
    case 'kinematic-velocity':y=p.v0+p.a0*x+p.j*x*x/2;break;
    case 'kinematic-acceleration':y=p.a0+p.j*x;break;
    case 'drag-quadratic':{const vt=Math.sqrt(2*p.m*9.81/(p.Cd*p.rho*p.area));y=vt*Math.tanh(9.81*x/vt);break;}
    case 'drag-quadratic-acceleration':{const vt=Math.sqrt(2*p.m*9.81/(p.Cd*p.rho*p.area)),z=Math.exp(-2*9.81*x/vt);y=4*9.81*z/(1+z)**2;break;}
    case 'constant-work':y=p.F*p.distance*Math.cos(x);break;
    case 'em-plane-electric':y=p.peak*Math.cos(2*Math.PI*(x/p.wavelength-p.phase));break;
    case 'em-plane-magnetic':y=p.peak*Math.sqrt(extraMu*extraEpsilon)*Math.cos(2*Math.PI*(x/p.wavelength-p.phase));break;
    case 'vector-sum':y=Math.sqrt(Math.max(0,p.A*p.A+p.B*p.B+2*p.A*p.B*Math.cos(x)));break;
    case 'free-fall':y=p.h+p.v*x-4.905*x*x;if(y<0)return null;break;
    case 'circular':y=Math.hypot(x*x/p.r,p.at);break;
    case 'friction':return x<=p.mu*p.N?x:null;
    case 'work-linear':y=p.k*x*x/2;break;
    case 'power':y=p.F*x;break;
    case 'impulse':y=p.F*x;break;
    case 'center-mass':y=(p.m1*p.x1+p.m2*x)/(p.m1+p.m2);break;
    case 'rocket':y=p.u*Math.log(x);break;
    case 'angular-motion':y=p.r*(p.w+p.alpha*x);break;
    case 'rotation-energy':y=p.m*x*x*p.w*p.w/2;break;
    case 'rolling':y=Math.sqrt(2*9.81*x/(1+p.eta));break;
    case 'precession':y=p.m*9.81*p.r/(p.I*x);if(y/x>=.1)return null;break;
    case 'density':y=p.rho*x;break;
    case 'elastic':y=x*1e6/(p.Y*1e9);break;
    case 'buoyancy':y=p.rho*x*9.81;break;
    case 'bernoulli':y=p.rho*(p.v*p.v-(p.v/x)**2)/2;break;
    case 'expansion':y=p.alpha*1e-6*p.length*x;break;
    case 'heat':y=p.m*p.c*x;break;
    case 'first-law':y=p.Q-x;break;
    case 'heat-capacity':y=p.n*8.314462618*x;break;
    case 'conduction':y=p.k*p.A*p.dt/x;break;
    case 'string-speed':y=Math.sqrt(x/p.mu);break;
    case 'wave-power':y=p.mu*(2*Math.PI*p.f)**2*x*x*p.v/2;break;
    case 'standing':y=2*p.A*Math.sin(2*Math.PI*x/p.lambda)*Math.cos(2*Math.PI*p.f*p.t);break;
    case 'sound-speed':y=Math.sqrt(p.bulk*1e9/x);break;
    case 'sound-intensity':y=p.power/(4*Math.PI*x*x);break;
    case 'doppler':y=p.f*(343+p.vo)/(343-x);break;
    case 'mach':y=Math.asin(343/x);break;
    case 'interference-phase':y=2*p.A*Math.abs(Math.cos(x/2));break;
    case 'pipe-open':y=343/(2*x);break;
    case 'pipe-closed':y=343/(4*x);break;
    case 'mirror':return p.f===0||x===p.f?null:p.f*x/(x-p.f);
    case 'thin-film':y=Math.cos((4*Math.PI*p.n*x/p.lambda+p.phase)/2)**2;break;
    case 'diffraction':{const b=Math.PI*p.width*1e-6*Math.sin(x)/(p.lambda*1e-9);y=Math.abs(b)<1e-8?1:(Math.sin(b)/b)**2;break;}
    case 'grating':{const s=p.lambda*1e-9/(x*1e-6);return s>1?null:Math.asin(s);}
    case 'malus':y=p.intensity*Math.cos(x)**2;break;
    case 'dipole-field':y=extraKe*p.q*1e-6*(1/(x-p.a)**2-1/(x+p.a)**2);break;
    case 'ring-field':y=extraKe*p.q*1e-6*x/(p.radius*p.radius+x*x)**1.5;break;
    case 'electric-motion':y=p.q*1e-6*p.E*x*x/(2*p.m);break;
    case 'electric-flux':y=p.E*p.area*Math.cos(x);break;
    case 'sphere-field':return x===p.radius?null:x<p.radius?0:extraKe*p.q*1e-6/(x*x);
    case 'uniform-potential':y=-p.E*x;break;
    case 'dipole-potential':y=extraKe*p.q*1e-6*(1/(x-p.a)-1/(x+p.a));break;
    case 'dipole-energy':y=-p.p*1e-6*p.E*Math.cos(x);break;
    case 'rod-potential':y=2*extraKe*p.q*1e-6/p.length*Math.asinh(p.length/(2*x));break;
    case 'arc-potential':y=extraKe*p.q*1e-6/x;break;
    case 'ring-potential':y=extraKe*p.q*1e-6/Math.hypot(p.radius,x);break;
    case 'disk-potential':y=2*Math.PI*extraKe*p.sigma*1e-6*p.radius**2/(Math.hypot(p.radius,x)+Math.abs(x));break;
    case 'sphere-potential':y=extraKe*p.q*1e-6/Math.max(x,p.radius);break;
    case 'plate-capacitance':if(x*1e-3/Math.sqrt(p.area)>.1)return null;y=extraEpsilon*p.area/(x*1e-3);break;
    case 'dielectric-charge':y=p.Q/(x*p.C);break;
    case 'dielectric-voltage':y=x*p.C*1e-6*p.V;break;
    case 'capacitors-series':y=p.C1*x/(p.C1+x)*1e-6;break;
    case 'capacitors-parallel':y=(p.C1+x)*1e-6;break;
    case 'current-density':y=p.I/(x*1e-6);break;
    case 'resistor-power':y=x*x/p.R;break;
    case 'terminal-voltage':y=p.emf-x*p.internal;if(y<0)return null;break;
    case 'resistors-series':y=p.V/(p.R1+x);break;
    case 'resistors-parallel':y=p.V*(1/p.R1+1/x);break;
    case 'rc-discharge':y=p.C*1e-6*p.V*Math.exp(-x/(p.R*p.C*1e-6));break;
    case 'cyclotron':y=1.67262192369e-27*x/(1.602176634e-19*p.B);break;
    case 'velocity-selector':y=p.q*1e-6*(p.E-x*p.B);break;
    case 'wire-force':y=p.I*p.length*p.B*Math.sin(x);break;
    case 'loop-torque':if(!Number.isInteger(p.N))return null;y=p.N*p.I*p.area*p.B*Math.sin(x);break;
    case 'parallel-wires':y=extraMu*p.I1*p.I2/(2*Math.PI*x);break;
    case 'solenoid':y=extraMu*p.n*x;break;
    case 'displacement-current':y=extraEpsilon*p.area*x;break;
    case 'motional-emf':y=p.B*p.length*x;break;
    case 'ac-rms':y=p.V*Math.sin(2*Math.PI*x);break;
    case 'transformer':y=p.Vp*x;break;
    case 'self-induction':y=-p.L*x;break;
    case 'mutual-induction':y=-p.M*x;break;
    case 'inductor-energy':y=p.L*x*x/2;break;
    case 'lr-growth':y=p.V/p.R*(-Math.expm1(-p.R*x/p.L));break;
    case 'lr-decay':y=p.I*Math.exp(-p.R*x/p.L);break;
    case 'lc-charge':y=1e-6*Math.cos(x/Math.sqrt(p.L*p.C*1e-6));break;
    case 'ac-reactance':y=x*p.L-1/(x*p.C*1e-6);break;
    case 'drag-acceleration':y=9.81*Math.exp(-p.b*x/p.m);break;
    case 'induced-flux-rate':y=Math.PI*Math.min(x,p.radius)**2*p.rate;break;
    case 'drag-linear':y=p.m*9.81/p.b*(-Math.expm1(-p.b*x/p.m));break;
    case 'conduction-cylinder':y=2*Math.PI*p.k*p.length*p.dt/Math.log(x);break;
    case 'conduction-series':y=p.area*p.dt/(p.L1/p.k1+x/p.k2);break;
    case 'solid-sphere-field':y=extraKe*p.q*1e-6*(x<=p.radius?x/p.radius**3:1/x**2);break;
    case 'solid-sphere-potential':y=extraKe*p.q*1e-6*(x<=p.radius?(3-x*x/p.radius**2)/(2*p.radius):1/x);break;
    case 'line-field':y=p.lambda*1e-6/(2*Math.PI*extraEpsilon*x);break;
    case 'capacitance-cylinder':if(p.inner*x/p.length>.1)return null;y=2*Math.PI*extraEpsilon*p.length/Math.log(x);break;
    case 'capacitance-sphere':y=4*Math.PI*extraEpsilon*p.inner*x/(x-1);break;
    case 'loop-axis-field':y=extraMu*p.I*p.radius**2/(2*(p.radius**2+x*x)**1.5);break;
    case 'finite-wire-field':y=extraMu*p.I/(2*Math.PI*p.a)*(x/2)/Math.hypot(p.a,x/2);break;
    case 'induced-electric':y=-p.rate/2*(x<=p.radius?x:p.radius**2/x);break;
    case 'kirchhoff-branches':y=(p.E1/p.R1+x/p.R2)/(1/p.R1+1/p.R2+1/p.R3);break;
    default:return null;
  }
  return Number.isFinite(y)?y:null;
}
