import {Button,Input,Select} from './index';
import {MathFormula} from './math-formula';
import type {ChemistryView} from '../data/chemistry-observation';
type State=ChemistryView['views'][string];
export const SPECIALISTS:Record<string,{question:string;limit:string}>={
 '5.6':{question:'온도와 몰질량을 바꾸면 제곱평균제곱근 속도는 어떻게 달라지는가?',limit:'이상기체의 병진 운동 모형이다. 분포·충돌의 실제 시간 진화나 비이상기체의 인력을 계산하지 않는다.'},
 '11.7':{question:'경계에 걸친 원자는 단위세포 안의 원자 수에 얼마나 기여하는가?',limit:'단원자 입방 구조의 대표 비교이다. 격자점과 원자 기저는 같은 개념이 아니다.'},
 '11.8':{question:'겉모양이 비슷한 결정에서 원자 종류·기저·배위수는 어떻게 다른가?',limit:'구조의 대응을 문장·분율 좌표로 읽는 대표 비교이다. 임의 결정의 3D 엔진·회절 계산은 구현하지 않았다.'},
 '19.2':{question:'갈바니 전지에서 전자와 이온은 각각 어디로 이동하는가?',limit:'Zn/Cu 대표 전지의 자발적인 방향을 설명한다. 실제 농도·전극 상태의 전위는 Nernst 관찰에서 별도로 판단한다.'},
 '20.7':{question:'핵분열의 연쇄 지속 조건과 핵융합의 반응 장벽은 어떻게 다른가?',limit:'과정·필요 조건의 비교이며 핵반응률·임계질량·원자로의 실제 계산은 아니다.'},
 '22.5':{question:'같은 배위식에서 cis와 trans의 리간드 위치는 어떻게 다른가?',limit:'[Pt(NH₃)₂Cl₂] 정사각 평면의 기하 이성질체만 조작 비교한다. 거울상·결합·이온화 이성질체의 전 범위는 별도 설명으로 남는다.'},
};
const CELLS=[['sc','단순 입방','8 꼭짓점 × 1/8 = 1','6','a = 2r'],['bcc','체심 입방','8 꼭짓점 × 1/8 + 1 중심 = 2','8','√3 a = 4r'],['fcc','면심 입방','8 꼭짓점 × 1/8 + 6 면 × 1/2 = 4','12','√2 a = 4r']];
const CRYSTALS=[['nacl','NaCl','Cl⁻의 FCC 배열과 모든 팔면체 틈의 Na⁺','Na⁺:Cl⁻ = 1:1 · 각 배위수 6','기저가 서로 다르므로 단원자 FCC 원자 수를 그대로 총 이온 수로 쓰지 않는다.'],['cscl','CsCl','모서리 한 종류와 체중심 다른 종류의 이온','Cs⁺:Cl⁻ = 1:1 · 각 배위수 8','두 종류가 바뀌는 체중심 이동은 원래 구조의 병진 대칭이 아니다. 단원자 BCC 브라베 격자로 동일시하지 않는다.'],['zns','ZnS · 섬아연석','한 종류의 FCC와 사면체 틈 절반의 다른 종류','Zn:S = 1:1 · 각 배위수 4','사면체 틈을 모두 채우지 않는다.'],['diamond','다이아몬드','FCC 격자에 두 탄소 기저; 상대 분율 좌표 (0,0,0), (¼,¼,¼)','각 탄소 배위수 4 · 정사면체 연결','같은 탄소 원자라도 기저를 하나로 지우면 연결을 잃는다.'],['close','조밀쌓임','HCP: ABAB… / CCP: ABCABC…','이상적인 구 쌓임의 배위수 모두 12','배위수가 같아도 층 순서가 같다거나 두 격자가 동치인 것은 아니다.']];
const CELL_STEPS=['Zn 전극에서 Zn → Zn²⁺ + 2e⁻ 산화가 일어난다. 산화 전극이 anode이다.','전자는 외부 도선으로 Zn에서 Cu로 간다. 전해질을 통한 전자 이동으로 그리지 않는다.','Cu 전극에서 Cu²⁺ + 2e⁻ → Cu 환원이 일어난다. 환원 전극이 cathode이다.','염다리는 전하 축적을 줄인다. 이 대표 전지에서 음이온은 Zn 쪽, 양이온은 Cu 쪽으로 이동한다.','전체 반응은 Zn + Cu²⁺ → Zn²⁺ + Cu이다. 갈바니 전지에서 anode는 음극·cathode는 양극이다. 전해 전지에도 산화/환원 정의는 유지되지만 부호는 다르다.'];
const NUCLEAR=[['fission','핵분열','중성자 흡수 → 무거운 핵의 분열 → 분열 조각·중성자 방출 → 다음 핵의 반응','다음 세대에 반응을 일으키는 중성자 수가 손실과 경쟁한다. 연쇄가 유지될 조건과 질량·기하·흡수·감속을 구별한다.','A와 Z의 보존만으로 연쇄 지속·임계 또는 실제 발생을 증명하지 않는다.'],['fusion','핵융합','가벼운 핵들의 접근 → 전기적 반발 장벽과 경쟁 → 핵 결합 및 에너지 변화','에너지 방출 가능성과 충분한 반응률은 별개이다. 고온 등 반응을 가능하게 하는 조건이 추가로 필요하다.','결합에너지의 이득만으로 점화·에너지 순이득을 보장하지 않는다.']];
export function ChemistrySpecialist({section,value,update}:{section:string;value:State;update:(x:Partial<State>)=>void}){
 const spec=SPECIALISTS[section];if(!spec)return null;
 const choice=value.molecule;const set=(key:string)=>update({molecule:key});
 return <article className="chem-calculation" data-specialist={section}><h4>{spec.question}</h4>
 {section==='5.6'?<Kinetic value={value} update={update}/>:section==='11.7'?<><Select label="단위세포 비교" value={CELLS.some(c=>c[0]===choice)?choice:'sc'} onChange={e=>set(e.target.value)}>{CELLS.map(c=><option value={c[0]} key={c[0]}>{c[1]}</option>)}</Select>{CELLS.filter(c=>c[0]===(CELLS.some(c=>c[0]===choice)?choice:'sc')).map(c=><section key={c[0]} data-observation-region="readout"><h5>{c[1]}</h5><p>원자 기여: {c[2]}</p><p>배위수: {c[3]}</p><p>동일 구가 접촉하는 단원자 모형: {c[4]}</p><p className="prose">꼭짓점 1/8, 면 1/2, 모서리 1/4, 세포 내부 1의 기여는 각각 이웃 세포에 공유되는 개수에서 나온다.</p></section>)}</>:section==='11.8'?<Compare label="결정 구조 비교" rows={CRYSTALS} choice={choice} set={set}/>:section==='19.2'?<><div className="chem-module"><p>Zn | Zn²⁺ ‖ Cu²⁺ | Cu</p><p>외부 도선의 전자: Zn → Cu</p><p>염다리의 음이온: Zn 쪽 / 양이온: Cu 쪽</p></div><Steps steps={CELL_STEPS} value={value} update={update}/></>:section==='20.7'?<Compare label="핵반응 과정 비교" rows={NUCLEAR} choice={choice} set={set}/>:<><Select label="기하 이성질체" value={choice==='trans'?'trans':'cis'} onChange={e=>set(e.target.value)}><option value="cis">cis · Cl이 이웃한다</option><option value="trans">trans · Cl이 마주 본다</option></Select><svg viewBox="0 0 440 300" role="img" aria-label={`정사각 평면 ${choice==='trans'?'trans':'cis'} [Pt(NH3)2Cl2]. 같은 사각 테두리가 아니라 리간드 배치가 판단 근거이다.`}>{[[220,40],[370,150],[220,260],[70,150]].map(([x,y],i)=><g key={i}><line x1="220" y1="150" x2={x} y2={y} stroke="currentColor"/><text x={x} y={y} textAnchor="middle" fill="currentColor">{(choice==='trans'?[0,2]:[0,1]).includes(i)?'Cl':'NH₃'}</text></g>)}<circle cx="220" cy="150" r="26" fill="var(--color-surface)" stroke="currentColor"/><text x="220" y="156" textAnchor="middle" fill="currentColor">Pt</text></svg><p className="prose">배위식·원자 수는 유지되지만 두 Cl의 상대 위치는 cis 90°, trans 180°로 다르다. 이 평면 배치의 회전만으로 서로 겹치게 할 수 없다. 이 그림을 거울상 이성질체의 일반 판정으로 사용하지 않는다.</p></>}
 <p className="prose" data-observation-region="reasoning">{spec.limit} 관측 구성은 설계 제안이며 실제 측정·일반 증명·학습 효과의 증거가 아니다.</p>{section!=='5.6'&&<Button onClick={()=>update({molecule:'water',step:0})}>이 비교·단계만 초기화</Button>}</article>;
}
function Compare({label,rows,choice,set}:{label:string;rows:string[][];choice:string;set:(x:string)=>void}){const row=rows.find(r=>r[0]===choice)??rows[0];return <><Select label={label} value={row[0]} onChange={e=>set(e.target.value)}>{rows.map(r=><option key={r[0]} value={r[0]}>{r[1]}</option>)}</Select><section data-observation-region="readout"><h5>{row[1]}</h5><p className="prose">{row[2]}</p><p className="prose">{row[3]}</p><p className="prose">조건·주의: {row[4]}</p></section></>;}
function Steps({steps,value,update}:{steps:string[];value:State;update:(x:Partial<State>)=>void}){const step=Math.min(value.step,steps.length-1);return <><ol>{steps.map((s,i)=><li key={i} aria-current={step===i?'step':undefined}><p className="prose">{s}</p></li>)}</ol><p>현재 단계 {step+1} / {steps.length}</p><div className="chem-actions"><Button disabled={step===0} onClick={()=>update({step:step-1})}>이전 단계</Button><Button disabled={step===steps.length-1} onClick={()=>update({step:step+1})}>다음 단계</Button></div></>;}
export function kineticRMS(t:number,m:number){return Math.sqrt(3*8.314462618*t/(m/1000));}
function Kinetic({value,update}:{value:State;update:(x:Partial<State>)=>void}){
 const t=value.values.T??300,m=value.values.M??28;const valid=t>0&&m>0&&Number.isFinite(t)&&Number.isFinite(m);const v=valid?kineticRMS(t,m):null;
 const commit=(key:string,raw:string)=>{const x=Number(raw);if(raw.trim()&&Number.isFinite(x)&&x>0&&x<=(key==='T'?5000:1000))update({values:{...value.values,[key]:x}});};
 return <><MathFormula tex="u_{\\mathrm{rms}}=\\sqrt{\\frac{3RT}{M}},\\qquad \\langle E_{\\mathrm{trans}}\\rangle=\\tfrac32 kT"/>{[['T','절대온도','K',t,5000],['M','몰질량','g/mol',m,1000]].map(([key,label,unit,n,max])=><Input key={String(key)} label={`${label} (${unit})`} inputMode="decimal" value={value.drafts[String(key)]??String(n)} onChange={e=>update({drafts:{...value.drafts,[String(key)]:e.target.value}})} onBlur={e=>{if(!e.currentTarget.dataset.composing)commit(String(key),e.target.value);}} onCompositionStart={e=>{e.currentTarget.dataset.composing='1';}} onCompositionEnd={e=>{delete e.currentTarget.dataset.composing;}} onKeyDown={e=>{if(e.key==='Enter'&&!e.nativeEvent.isComposing)commit(String(key),e.currentTarget.value);}} hint={`0보다 크고 ${max} 이하; 설명용 범위`} error={value.drafts[String(key)]!==undefined&&(!value.drafts[String(key)].trim()||!Number.isFinite(Number(value.drafts[String(key)]))||Number(value.drafts[String(key)])<=0||Number(value.drafts[String(key)])>Number(max))?'입력을 확인할 때까지 확정값을 유지한다.':undefined}/>)}<Select label="이상기체 가정" value={value.condition} onChange={e=>update({condition:e.target.value as State['condition']})}><option value="fulfilled">모형 조건 충족</option><option value="unknown">확인 전</option><option value="violated">조건 위반</option></Select>{[['T','절대온도',t,1,5000],['M','몰질량',m,1,1000]].map(([key,label,n,min,max])=><label className="chem-slider" key={String(key)}>{label} 탐색<input type="range" aria-label={`${label} 탐색`} min={Number(min)} max={Number(max)} step="1" value={Number(n)} onChange={e=>update({values:{...value.values,[String(key)]:Number(e.target.value)},drafts:{...value.drafts,[String(key)]:e.target.value}})}/></label>)}<output>{value.condition==='fulfilled'&&v!==null?`uᵣₘₛ = ${v.toPrecision(7)} m/s`:'이 모형 적용 판단 보류'}</output><p className="prose">몰질량은 계산 안에서 kg/mol로 바꾼다. 같은 온도에서 평균 병진 에너지는 같고, 무거운 입자의 제곱평균제곱근 속도는 작다. uᵣₘₛ는 평균 속력과 다르다. 300 K·28 g/mol은 비교용 초기값이다. 탐색 조절은 양의 정수 구간이며 정확 입력은 그 사이의 양의 실수도 허용한다.</p><Button onClick={()=>update({values:{...value.values,T:300,M:28},drafts:{...value.drafts,T:'300',M:'28'},condition:'fulfilled'})}>운동론 조건만 초기화</Button></>;
}
