import {useEffect,useRef,useState} from 'react';
import {getDocument,GlobalWorkerOptions,type PDFDocumentProxy} from 'pdfjs-dist';
import worker from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
import {CHEMISTRY} from '../domain/chemistry/catalog';
import {Button,Input} from './index';
import type {ChemistryView} from '../data/chemistry-observation';
import type {AppState} from '../domain/model';
import {readChemistryFile,keepChemistryFile} from '../data/chemistry-file';
GlobalWorkerOptions.workerSrc=worker;
/** Local-only source slice; no file transfer to a remote service or implicit material save. */
export function ChemistrySource({owner,page,initialOffset=0,value,onChange}:{owner:Pick<AppState,'namespace'|'userId'>;page:number;initialOffset?:number;value:ChemistryView['views'][string];onChange:(v:Partial<ChemistryView['views'][string]>)=>void}) {
 const [pdf,setPDF]=useState<PDFDocumentProxy|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(true),[p,setPage]=useState(value.values.page??page),[offset,setY]=useState(value.values.offset??initialOffset),[height,setHeight]=useState(14400),[scale,setZoom]=useState(value.zoom);
 const [sourceBlob,setSourceBlob]=useState<Blob|null>(null),[fileState,setFileState]=useState(''),[fileError,setFileError]=useState(''),[saving,setSaving]=useState(false);
 function setP(n:number){setPage(n);setY(0);onChange({values:{...value.values,page:n,offset:0}});}
 function setOffset(n:number){setY(n);onChange({values:{...value.values,page:p,offset:n}});}
 function setScale(n:number){setZoom(n);onChange({zoom:n});}
 const canvas=useRef<HTMLCanvasElement>(null),epoch=useRef(0),opened=useRef<PDFDocumentProxy|null>(null),alive=useRef(true);
 async function open(bytes:Uint8Array,kept=false){const token=++epoch.current;setBusy(true);setError('');try{const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',new Uint8Array(bytes).buffer))].map(x=>x.toString(16).padStart(2,'0')).join('');if(hash!==CHEMISTRY.source.source_sha256)throw Error('기존 근거의 PDF와 SHA-256이 다르다. 다른 파일을 같은 원문으로 처리하지 않는다.');const blob=new Blob([new Uint8Array(bytes).buffer],{type:'application/pdf'});const document=await getDocument({data:bytes}).promise;if(token!==epoch.current){await document.loadingTask.destroy();return;}await opened.current?.loadingTask.destroy();opened.current=document;setPDF(document);setSourceBlob(blob);setFileState(kept?'이 기기에 보관한 같은 원문을 다시 열었다.':'현재 원문은 열린 화면에 있다. 기기 보관을 선택할 수 있다.');}catch(e){if(token===epoch.current)setError(String(e));}finally{if(token===epoch.current)setBusy(false);}}
 async function retainFile(){if(!sourceBlob)return;const token=epoch.current;setSaving(true);setFileError('');try{await keepChemistryFile(owner,sourceBlob);if(alive.current&&token===epoch.current)setFileState('이 기기에 원문 보관됨 · 다시 열기에서도 같은 파일을 사용한다. 서버에 전송하지 않았다.');}catch(e){if(alive.current)setFileError(String(e)+' 현재 열린 원문은 유지한다. 다시 시도할 수 있다.');}finally{if(alive.current)setSaving(false);}}
 useEffect(()=>{alive.current=true;let active=true;const controller=new AbortController();const start=epoch.current;void(async()=>{try{const local=await readChemistryFile(owner);if(!active||epoch.current!==start)return;if(local){await open(new Uint8Array(await local.arrayBuffer()),true);return;}}catch(e){if(active)setFileError(String(e)+' 보관된 원문은 덮어쓰지 않았다.');}try{const r=await fetch(`${import.meta.env.BASE_URL}__chemistry-source/pdf`,{signal:controller.signal});if(!r.ok||!r.headers.get('content-type')?.includes('application/pdf'))throw Error('원문 파일을 이 기기에 선택하면 읽을 수 있다. 원문은 공개 앱에 포함하거나 서버에 자동 전송하지 않는다.');const b=new Uint8Array(await r.arrayBuffer());if(active&&epoch.current===start)await open(b);}catch(e){if(active&&epoch.current===start){setError(String(e));setBusy(false);}}})();return()=>{active=false;alive.current=false;controller.abort();epoch.current++;void opened.current?.loadingTask.destroy();};},[owner.namespace,owner.userId]);
 useEffect(()=>{if(!pdf||!canvas.current)return;let active=true;let task:ReturnType<Awaited<ReturnType<PDFDocumentProxy['getPage']>>['render']>|undefined;const target=canvas.current;void pdf.getPage(p).then(async page=>{if(!active)return;const natural=page.getViewport({scale:1});setHeight(natural.height);const viewport=page.getViewport({scale:scale*2});target.width=Math.ceil(viewport.width);target.height=1800;task=page.render({canvas:target,viewport,transform:[1,0,0,1,0,-offset*scale*2]});await task.promise;if(active)setError('');}).catch(e=>{if(active)setError(String(e));});return()=>{active=false;task?.cancel();};},[pdf,p,offset,scale]);
 return <section aria-label="일반화학 PDF 원문"><p>{busy?'원본 SHA-256을 확인하고 여는 중이다.':pdf?fileState:'원문 연결이 아직 열리지 않았다.'}</p>{error&&<p role="alert">{error}</p>}{fileError&&<p role="alert">{fileError}</p>}<label>원본 PDF 직접 선택<input type="file" accept="application/pdf" onChange={e=>{const file=e.target.files?.[0];if(file)void file.arrayBuffer().then(b=>open(new Uint8Array(b))).catch(e=>setError(String(e)));}}/></label>{pdf&&<><Button onClick={()=>void retainFile()} disabled={saving}>{saving?'원문 보관 확인 중':'이 기기에 원문 보관'}</Button><p>원문 보관은 이 사용자·공간의 기존 자료 저장 경로를 사용한다. 관찰 선택·읽기 위치·메모와 별개이며 초기화가 원문 파일을 지우지 않는다.</p><Input label="PDF 페이지 (책 인쇄 쪽과 구별)" type="number" min={1} max={pdf.numPages} value={p} onChange={e=>{const n=Number(e.target.value);if(Number.isInteger(n)&&n>=1&&n<=pdf.numPages){setP(n);}}}/><p>긴 PDF 페이지 안의 위치: {offset} pt / {height} pt</p><label>원문 세로 위치<input type="range" min={0} max={Math.max(0,height-900/scale)} step={100} value={offset} onChange={e=>setOffset(Number(e.target.value))}/></label><div className="chem-actions"><Button onClick={()=>setOffset(Math.max(0,offset-700/scale))}>앞 부분</Button><Button onClick={()=>setOffset(Math.min(Math.max(0,height-900/scale),offset+700/scale))}>다음 부분</Button><Button onClick={()=>setScale(Math.min(3,scale*1.25))}>원문 확대</Button><Button onClick={()=>setScale(Math.max(0.5,scale/1.25))}>원문 축소</Button></div><div className="chem-source-scroll"><canvas ref={canvas} style={{width:`${402*scale}px`}} aria-label="원문 PDF의 현재 부분"/></div><p>이 캔버스는 원문 그림을 대조하는 면이다. 접근 가능한 개념·관계·조건 설명은 원래 질문 화면에서 함께 읽는다.</p></>}</section>;
}
