import type {PhysicsSourceOwner} from '../data/physics-source-file';
import {PhysicsDeviceSource} from './physics-device-source';
import { useEffect, useRef, useState } from 'react';
import { physicsCatalog, physicsMapping, observationById } from '../domain/physics-observations';
import { physicsSectionRange, physicsConceptReading, physicsSectionItems, physicsPageLabel, physicsSectionSourceLinks } from '../domain/physics-reading';
import type { PhysicsReadingView } from '../data/physics-observation-view';
import { Button, Select, Textarea, ErrorState, LoadingState } from './index';
import { ConceptText } from './concept-text';
import { PhysicsSourcePage } from './physics-source-page';
import { MathFormula } from './math-formula';
/** Reading choices select a source or a meaning; they never record completion. */
export function PhysicsSectionReader({id,view,onChange,onObservation,owner}:{owner:PhysicsSourceOwner;id:string;view:PhysicsReadingView;onChange:(patch:Partial<PhysicsReadingView>)=>void;onObservation:(id:string,sourcePage?:number)=>void}) {
  const range=physicsSectionRange(id)!,mapping=physicsMapping.find(s=>s.id===id)!,concept=physicsConceptReading(id);
  const section=physicsCatalog.chapters.flatMap(ch=>ch.sections).find(s=>s.id===id)!;
  const [text,setText]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false),[retry,setRetry]=useState(0);
  const local=import.meta.env.DEV||new URLSearchParams(location.search).get('physicsSource')==='local',pageRef=useRef<HTMLHeadingElement>(null);
  const [itemQuery,setItemQuery]=useState('');const sourceItems=physicsSectionItems(id).filter(s=>s.label.toLowerCase().includes(itemQuery.toLowerCase()));
  useEffect(()=>{const controller=new AbortController();setText('');setError('');if(!local){setError('이 실행본에는 원문 추출본이 포함되지 않았다. 이 절의 원본 PDF 위치는 아래에서 확인할 수 있다.');return;}setLoading(true);fetch(`${import.meta.env.BASE_URL}__physics/page/${view.page}`,{signal:controller.signal}).then(async r=>{if(!r.ok)throw Error();const v:unknown=await r.json();if(!v||typeof v!=='object'||typeof (v as {text?:unknown}).text!=='string')throw Error();if(!controller.signal.aborted)setText((v as {text:string}).text);}).catch(()=>{if(!controller.signal.aborted)setError('이 쪽의 원문을 불러오지 못했다. 읽기 위치와 메모는 유지했다.');}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[view.page,local,retry]);
  const selected=concept?.steps.find(s=>s.id===view.focus);
  return <article className="physics-section-reader">
    <header data-observation-region="question"><p className="muted">{section.section} {section.ko} · 책 시작 {range.printedStart}쪽 · PDF {range.startPdf}–{range.endPdf}쪽</p><h3>{mapping.question}</h3><div className="physics-prose"><ConceptText text={concept?.conditions??mapping.conditions}/></div></header>
    {concept&&<section className="physics-module" data-observation-region="visual"><h4>{concept.mode==='process'?'과정과 근거':'대상과 조건의 비교'}</h4><nav className="physics-observation-tools" aria-label={concept.mode==='process'?'과정 읽기 위치':'비교할 대상'}>{concept.steps.map((s,i)=><Button key={s.id} aria-pressed={view.focus===s.id} onClick={()=>onChange({focus:view.focus===s.id?'':s.id})}>{concept.mode==='process'?`${i+1}. `:''}{s.name}</Button>)}</nav><p className="muted">{concept.mode==='process'?'원문 과정의 순서를 따른다. 선택은 읽기 위치이다.':'비교 항목에는 시간 순서·우열·완료 순서를 부여하지 않는다.'}</p>{(selected?[selected]:concept.steps).map(s=><div className="physics-module" key={s.id}><h4>{s.name}</h4><p className="physics-prose">{s.text}</p>{s.tex&&<MathFormula tex={s.tex}/>}</div>)}{concept.relationships.length>0&&<div className="physics-connections" aria-label="개념 사이의 관계">{concept.relationships.map((r,i)=><p key={i} className="physics-prose"><strong>{concept.steps.find(s=>s.id===r.fromId)?.name}</strong><span aria-hidden="true"> → </span><span className="sr-only">에서 다음 개념으로 연결된다. </span><strong>{concept.steps.find(s=>s.id===r.toId)?.name}</strong><br/>{r.text}</p>)}</div>}{selected&&<Button onClick={()=>onChange({focus:''})}>관계 전체 다시 보기</Button>}<p className="physics-prose">{concept.limits}</p><p className="muted">{concept.sourceScope}</p></section>}
    {mapping.observations.length>0&&<section className="physics-module"><h4>이 절의 계산과 연결</h4><p className="physics-prose">원문에서 조건을 읽은 뒤 같은 절에 연결된 수식·그래프 관찰을 열 수 있다. 각 관찰의 초기조건과 포함 범위를 확인한다.</p><div className="physics-observation-tools">{mapping.observations.map(o=><Button key={o} onClick={()=>onObservation(o)}>계산 관찰 열기 · {observationById(o)?.name}</Button>)}</div></section>}
    <section data-observation-region="controls"><Select label="이 절에서 적용할 조건 확인" value={view.condition} onChange={e=>onChange({condition:e.target.value as PhysicsReadingView['condition']})}><option value="unknown">아직 확인하지 않음</option><option value="confirmed">현재 목적에서 조건 확인</option><option value="violated">현재 목적에서 조건 위반</option></Select><p className="muted">조건 확인은 사용자의 메모 상태이다. 법칙의 참·거짓, 정답, 공부 완료 또는 숙달을 자동 판정하지 않는다.</p></section>
    <section className="physics-module" data-observation-region="reference"><h4 ref={pageRef} tabIndex={-1}>{view.sourceMode==='image'?'원본 그림·수식':'이전 본문 추출본'} · {physicsPageLabel(view.page)}</h4><p className="muted">{range.pageBoundary} 원본 그림·수식 조판은 추출 글로 확인되지 않는다.</p><div className="physics-observation-tools"><Button disabled={view.page<=range.startPdf} onClick={()=>onChange({page:view.page-1})}>이 절의 앞쪽</Button><Select label="이 절 원문 PDF 페이지" value={view.page} onChange={e=>onChange({page:Number(e.target.value)})}>{Array.from({length:range.endPdf-range.startPdf+1},(_,i)=><option key={i} value={range.startPdf+i}>{physicsPageLabel(range.startPdf+i)}</option>)}</Select><Button disabled={view.page>=range.endPdf} onClick={()=>onChange({page:view.page+1})}>이 절의 뒤쪽</Button></div><div className="physics-observation-tools"><Button aria-pressed={view.sourceMode!=='image'} onClick={()=>onChange({sourceMode:'text'})}>본문 추출본 읽기</Button><Button aria-pressed={view.sourceMode==='image'} onClick={()=>onChange({sourceMode:'image'})}>원본 그림·수식 펼치기</Button></div>{!local?<PhysicsDeviceSource owner={owner} page={view.page}/>:view.sourceMode==='image'?<PhysicsSourcePage page={view.page}/>:loading?<LoadingState message="원문 쪽을 여는 중이다."/>:error?<><ErrorState message={error}/><Button onClick={()=>setRetry(v=>v+1)}>원문 다시 불러오기</Button></>:<pre className="physics-source-text physics-prose">{text||'이 쪽의 추출 글이 비어 있다. 원본 도형·이미지는 PDF에서 별도로 확인해야 한다.'}</pre>}<p className="muted">{physicsCatalog.source.localPath}</p></section>
    {physicsSectionSourceLinks(id).length>0&&<details className="physics-module physics-verified-links"><summary>원문 관계와 대조한 관찰 연결 {physicsSectionSourceLinks(id).length}개</summary><p className="muted">아래 항목의 원문 관계·조건·기호를 대조했다. 확인 방법과 실제 구현 범위를 함께 읽는다.</p>{physicsSectionSourceLinks(id).map(link=><section className="physics-module" key={link.id}><h4>{link.label} · {link.question}</h4><p className="muted">{link.sourcePurpose}</p>{link.sourceTex&&<MathFormula tex={link.sourceTex}/>}<p className="physics-prose">{link.relation}</p><p className="physics-prose">{link.conditions}</p><p className="muted">교재 밖 · 관찰 설계와 적용 범위</p><p className="physics-prose">{link.difference}</p><p className="muted">{link.classification} · {link.verification.includes('pixel')?'원문 글과 해당 원본 그림·수식 대조':'원문 글의 관계·조건 대조'}</p><div className="physics-observation-tools"><Button onClick={()=>onChange({page:link.pdf,sourceMode:'image'})}>{physicsPageLabel(link.pdf)} 원본 열기</Button>{link.observations.map(o=><Button key={o} onClick={()=>onObservation(o,link.pdf)}>대응 관찰 · {observationById(o)?.name}</Button>)}</div></section>)}</details>}
    <details className="physics-module"><summary>이 절 범위에서 찾은 원문 식 번호·그림 표제 {physicsSectionItems(id).length}개</summary><p className="muted">번호 후보와 대조한 관계를 구별한다. 대조 표시는 그 항목의 확인 범위이며 책 전체의 검증 완료가 아니다. 경계 쪽에는 이웃 절 내용도 있다.</p><label>원문 번호 찾기<input value={itemQuery} onChange={e=>setItemQuery(e.target.value)}/></label>{sourceItems.map(s=><div className="physics-module" key={s.id}><Button onClick={()=>onChange({page:s.pdf})}>{s.kind==='equation'?'식':'그림'} {s.label} · {physicsPageLabel(s.pdf)} 열기</Button><p className="physics-source-text physics-prose">{physicsPageLabel(s.pdf)} · 추출본 {s.line}행 · {s.verification==='text-label-candidate'?'번호 후보 · 판단 보류':'관계·조건 대조 · '+s.classification}</p></div>)}{!sourceItems.length&&<p>해당 번호 후보가 없다. 원문 페이지에서 확인할 수 있다.</p>}</details><Textarea className="paper-memo" label="이 절의 조건·관계 메모" value={view.memo} onChange={e=>onChange({memo:e.target.value})}/>
    <div className="physics-observation-tools"><Button onClick={()=>pageRef.current?.focus()}>현재 원문 쪽으로 돌아가기</Button><Button onClick={()=>document.querySelector('.physics-reading-modal [data-observation-region="question"]')?.scrollIntoView({block:'start'})}>이 절의 질문으로 돌아가기</Button></div>
    <p className="muted">읽기 위치·선택·조건 메모는 이 기기에 보관한다. 서버·다기기 동기화는 하지 않는다.</p>
  </article>;
}
