import { useEffect, useState } from 'react';
import type { AppState } from '../domain/model';
import { scheduleDeadline, scheduleLabels, scheduleWorkSteps, workLabels, type LearningSchedule, type ScheduleKind } from '../domain/learning-schedule';
import { addDays, calendarFile, koreanDay, monthDays, orderSchedules, remainingTime, schedulePending, deadlinePending } from '../domain/schedule-management';
import { downloadCalendar, readScheduleView, saveScheduleView, type ScheduleView } from '../data/schedule-view';
import { Button, Card, Input, Select } from './index';
import type { ScheduleNotificationPort } from '../data/schedule-notifications';
import { ScheduleNotifications } from './schedule-notifications';

export function ScheduleDashboard({data,schedules,edit,update,create,restore,notifications,checks,onCheck,goals,disabled=false}: {data:AppState;schedules:LearningSchedule[];edit:(s:LearningSchedule)=>void;update:(s:LearningSchedule,p:Partial<LearningSchedule>,reason?:string)=>void;create:(kind?:ScheduleKind)=>void;restore:(s:LearningSchedule,index:number)=>void;checks?:{id:string;subjectId:string;at:string}[];goals?:{targetId:string}[];onCheck:(subjectId:string)=>void;notifications?:ScheduleNotificationPort;disabled?:boolean}) {
 const [now,setNow]=useState(()=>new Date().toISOString()),[view,setView]=useState(()=>readScheduleView(data,koreanDay().slice(0,7))),[selected,setSelected]=useState(''),[limit,setLimit]=useState(20),[notice,setNotice]=useState(''),[checkSubject,setCheckSubject]=useState('');
 useEffect(()=>{const tick=()=>setNow(new Date().toISOString()),timer=window.setInterval(tick,60000);window.addEventListener('focus',tick);document.addEventListener('visibilitychange',tick);return()=>{window.clearInterval(timer);window.removeEventListener('focus',tick);document.removeEventListener('visibilitychange',tick);};},[]);
 const today=koreanDay(now),active=schedules.filter(schedulePending),overdue=active.filter(s=>deadlinePending(s)&&s.dueDate&&Date.parse(scheduleDeadline(s)!)<Date.parse(now)),unknown=active.filter(s=>!s.dueDate),soon=active.filter(s=>deadlinePending(s)&&s.dueDate>=today&&s.dueDate<=addDays(today,7));
 const patchView=(p:Partial<ScheduleView>)=>{const next={...view,...p};setView(next);setLimit(20);setSelected('');try{saveScheduleView(data,next);setNotice('');}catch{setNotice('보기 설정을 이 기기에 저장하지 못했습니다. 일정 원문은 유지됩니다.');}};
 const filtered=orderSchedules(schedules.filter(s=>(view.status==='trash'?!!s.deletedAt:!s.deletedAt&&s.status===view.status)&&(view.kind==='all'||view.kind==='unknown'&&!s.dueDate||view.kind===s.kind)&&(!view.query||[s.name,s.note,s.taskText,data.subjects.find(sub=>sub.id===s.subjectId)?.name].some(v=>v?.toLocaleLowerCase().includes(view.query.toLocaleLowerCase())))));
 const shown=selected?filtered.filter(s=>s.dueDate===selected||!s.dueDate&&s.reviewDate===selected):filtered;
 const monthChange=(offset:number)=>{const date=new Date(`${view.month}-01T00:00:00Z`);date.setUTCMonth(date.getUTCMonth()+offset);patchView({month:date.toISOString().slice(0,7)});};
 return <section aria-label="일정 관리" className="schedule-dashboard">
   <div className="schedule-summary" aria-label="일정 요약"><span>일주일 안 {soon.length}개</span><span>기한 지남 {overdue.length}개</span><span>기한 미정 {unknown.length}개</span></div>
   <p className="muted">강의 재생 확인 {schedules.filter(s=>!s.deletedAt&&s.states.watch==='done').length}개 · 학습 확인 {schedules.filter(s=>!s.deletedAt&&s.states.learn==='done').length}개 · 필기 확인 {schedules.filter(s=>!s.deletedAt&&s.states.notes==='done').length}개 · 출석 확인 {schedules.filter(s=>!s.deletedAt&&s.states.attendance==='done').length}개</p>
   <div className="actions"><Button onClick={()=>create('assignment')}>과제 추가</Button><Button onClick={()=>create('lecture')}>온라인 강의 추가</Button><Button onClick={()=>create('class')}>주차별 강의 추가</Button><Button onClick={()=>create()}>시험·과제·강의 일정 추가</Button></div>
   <details><summary>과목 공지 확인 기록</summary><p>새 과제·강의가 있는지 과목 공지를 확인한 뒤 남겨 주세요. 기한을 모르면 미정으로 등록할 수 있습니다.</p><Select label="공지 확인한 과목" value={checkSubject} onChange={e=>setCheckSubject(e.target.value)}><option value="">과목 선택</option>{data.subjects.filter(s=>!s.deletedAt).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</Select><Button disabled={!checkSubject||disabled} onClick={()=>{if(checkSubject)onCheck(checkSubject);}}>공지 확인했어요</Button><p className="muted">공지 확인은 과제 제출·출석 인정·새 과제 없음의 확인을 뜻하지 않습니다.</p>{data.subjects.filter(s=>!s.deletedAt).map(s=>{const latest=checks?.filter(c=>c.subjectId===s.id).at(-1);return latest&&<p key={s.id}>{s.name} · 마지막 공지 확인 {new Date(latest.at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}</p>;})}</details>
   <ScheduleNotifications data={data} schedules={schedules} port={notifications} disabled={disabled}/>
   <div className="schedule-toolbar"><Input label="일정 찾기" type="search" value={view.query} onChange={e=>patchView({query:e.target.value})}/><Select label="일정 종류 보기" value={view.kind} onChange={e=>patchView({kind:e.target.value})}><option value="all">모든 종류</option><option value="unknown">기한 미정 모아 보기</option>{Object.entries(scheduleLabels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</Select><Select label="일정 보관 상태" value={view.status} onChange={e=>patchView({status:e.target.value as ScheduleView['status']})}><option value="active">진행 중</option><option value="ended">보관함</option><option value="trash">휴지통</option></Select></div>
   <div className="actions"><Button aria-pressed={view.view==='list'} onClick={()=>patchView({view:'list'})}>목록</Button><Button aria-pressed={view.view==='calendar'} onClick={()=>patchView({view:'calendar'})}>달력</Button><Button onClick={()=>{downloadCalendar(calendarFile(schedules,now,`${data.namespace}-${data.userId}`));setNotice('현재 일정을 캘린더 파일로 저장했습니다. 파일을 추가한 캘린더에서 알림 설정을 확인해 주세요. 일정이 바뀌면 다시 내보내야 합니다.');}}>캘린더 파일 저장</Button></div>
   {view.view==='calendar'&&<div className="schedule-calendar"><div className="actions"><Button onClick={()=>monthChange(-1)} aria-label="이전 달">이전 달</Button><Input label="달력 월" type="month" value={view.month} onInput={e=>{if(e.currentTarget.value)patchView({month:e.currentTarget.value});}} onChange={e=>{if(e.target.value)patchView({month:e.target.value});}}/><Button onClick={()=>monthChange(1)} aria-label="다음 달">다음 달</Button><Button onClick={()=>patchView({month:today.slice(0,7)})}>이번 달</Button></div><div className="schedule-month" role="group" aria-label={`${view.month} 일정 달력`}>
     {['일','월','화','수','목','금','토'].map(day=><span key={day} className="schedule-weekday">{day}</span>)}
     {monthDays(view.month).map(day=>{const rows=filtered.filter(s=>s.dueDate===day||!s.dueDate&&s.reviewDate===day);return <button type="button" key={day} className="schedule-day" data-outside={!day.startsWith(view.month)} aria-pressed={selected===day} aria-current={day===today?'date':undefined} aria-label={`${day} · 일정 ${rows.length}개`} onClick={()=>{setSelected(selected===day?'':day);setLimit(20);}}><span>{Number(day.slice(-2))}</span><span className="schedule-day-count">{rows.length?`${rows.length}개`:''}</span></button>;})}
   </div><p className="muted">날짜를 누르면 아래에서 해당 일정을 봅니다. 시각이 없는 일정은 날짜만 표시합니다.</p>{selected&&<div className="actions"><strong>{selected} 일정</strong><Button onClick={()=>setSelected('')}>모든 날짜 보기</Button></div>}</div>}
   {notice&&<p role="status">{notice}</p>}
   <p className="muted">{shown.length}개 · 가까운 기한 순서입니다. 보관은 완료를 뜻하지 않습니다.</p>
   {!shown.length&&<p>{view.kind==='unknown'?'기한 미정 일정이 없습니다.':view.status==='trash'?'휴지통이 비어 있습니다.':'이 조건에 맞는 일정이 없습니다.'}</p>}
   <div className="learning-schedule-list">{shown.slice(0,limit).map(s=><Card key={s.id}>
     <p className="muted">{scheduleLabels[s.kind]} · {data.subjects.find(sub=>sub.id===s.subjectId)?.name}{s.week?` · ${s.week}주차`:''}</p><h3>{s.name}</h3>
     <p>{s.dueDate||'기한 미정'}{s.dueTime?` ${s.dueTime}`:''} · {remainingTime(s,now)} · {({exam:'시험일',submission:'제출 기한',attendance:'출석 기한',personal:'개인 목표',unknown:'기한 의미 미정'})[s.dueMeaning]}{s.weight!==null?` · 비중 ${Math.round(s.weight*100)}%`:''}</p>
     {s.opensDate&&<p className="muted">시작 가능: {s.opensDate}{s.opensTime?` ${s.opensTime}`:''}</p>}
     {!s.dueDate&&<p className="muted">공지 확인일: {s.reviewDate||'미정'}{s.reviewDate&&s.reviewDate<=today?' · 공지에서 기한을 확인해 주세요.':''}</p>}
     {s.taskText&&<p className="next-study-answer">해야 할 일: {s.taskText}</p>}{s.note&&<p className="next-study-answer">{s.note}</p>}
     {s.sourceUrl&&<a href={s.sourceUrl} target="_blank" rel="noopener noreferrer">공지·강의 열기</a>}
     {!s.deletedAt&&scheduleWorkSteps(s).map(step=><Select key={step} label={`${s.name}${s.week?` · ${s.week}주차`:''} · ${workLabels[step]}`} value={s.states[step]??'unknown'} onChange={e=>update(s,{states:{...s.states,[step]:e.target.value as 'unknown'|'done'|'not-done'}},`${workLabels[step]} 상태 수정`)}><option value="unknown">미확인</option><option value="not-done">아직 하지 않음</option><option value="done">직접 확인한 완료</option></Select>)}
     {s.targetIds.length>0&&<p className="muted">범위: {s.targetIds.map(id=>data.nodes.find(n=>n.id===id)?.name??id).join(', ')}</p>}
     {["exam","quiz"].includes(s.kind)&&s.targetIds.some(id=>!goals?.some(g=>g.targetId===id))&&<p className="muted">범위 중 수행 확인 기준이 없는 주제가 있습니다. ‘다음 공부’의 ‘확인할 내용 추가’에서 기준을 남기면 추천에 연결됩니다.</p>}
     <div className="actions">{s.deletedAt?<Button onClick={()=>update(s,{deletedAt:null},'휴지통에서 복원')}>일정 복원</Button>:<><Button variant="quiet" onClick={()=>edit(s)}>일정 수정</Button><Button variant="quiet" onClick={()=>update(s,{status:s.status==='active'?'ended':'active'},'보관 상태 수정')}>{s.status==='active'?'일정 보관':'일정 다시 열기'}</Button><Button variant="quiet" onClick={()=>update(s,{deletedAt:now},'휴지통으로 이동')}>휴지통으로 이동</Button></>}{!!s.history?.length&&<Button onClick={()=>restore(s,s.history!.length-1)}>마지막 변경 되돌리기</Button>}</div>
     {!!s.history?.length&&<details><summary>변경 이력 {s.history.length}개</summary>{s.history.slice().reverse().map((h,i)=><div key={`${h.at}-${i}`} className="learning-comparison"><p>{new Date(h.at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})} · {h.reason}</p><p>{h.previous.name} · 이전 기한 {h.previous.dueDate||'미정'} {h.previous.dueTime||''}</p><details><summary>이전 원문·상태 보기</summary><p className="next-study-answer">{h.previous.taskText}</p><p className="next-study-answer">{h.previous.note}</p><p>{scheduleWorkSteps(h.previous).map(step=>`${workLabels[step]}: ${{unknown:'미확인','not-done':'아직 하지 않음',done:'직접 확인한 완료'}[h.previous.states[step]||'unknown']}`).join(' · ')}</p></details><Button onClick={()=>restore(s,s.history!.length-1-i)}>이 기록으로 되돌리기</Button></div>)}</details>}
   </Card>)}</div>
   {shown.length>limit&&<Button onClick={()=>setLimit(v=>v+20)}>일정 더 보기 · 남은 {shown.length-limit}개</Button>}
 </section>;
}
