"""Rebuild the editable SVG and inline React wordmark with FontTools 4.60.2.

Run: python scripts/build-brand-wordmark.py
The OFL source font and design parameters live in assets/brand/.
"""
import json
from pathlib import Path
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.pens.boundsPen import BoundsPen

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / 'assets' / 'brand'
PARAMS = json.loads((ASSETS / 'wordmark-design.json').read_text())


def pair_spacing(font, left, right):
    """Reuse the font's kern feature, then apply the design's optical spacing."""
    if 'GPOS' not in font:
        return 0
    table = font['GPOS'].table
    indices = {i for record in table.FeatureList.FeatureRecord
               if record.FeatureTag == 'kern' for i in record.Feature.LookupListIndex}
    adjustment = 0
    for i in sorted(indices):
        lookup = table.LookupList.Lookup[i]
        for sub in lookup.SubTable:
            kind = lookup.LookupType
            if kind == 9:
                kind, sub = sub.ExtensionLookupType, sub.ExtSubTable
            if kind != 2 or left not in sub.Coverage.glyphs:
                continue
            if sub.Format == 1:
                pairs = sub.PairSet[sub.Coverage.glyphs.index(left)].PairValueRecord
                value = next((p.Value1 for p in pairs if p.SecondGlyph == right), None)
            else:
                c1 = sub.ClassDef1.classDefs.get(left, 0)
                c2 = sub.ClassDef2.classDefs.get(right, 0)
                value = sub.Class1Record[c1].Class2Record[c2].Value1
            adjustment += getattr(value, 'XAdvance', 0) if value else 0
    return adjustment


paths, bounds = [], []
cursor = 0
for role in ['name', 'suffix']:
    spec = PARAMS[role]
    font = TTFont(ASSETS / 'InterVariable.ttf')
    # Interpolate only the thirteen logo glyphs, not the font's entire character set.
    glyphs, cmap = font.getGlyphSet(location=spec['axes']), font.getBestCmap()
    units = font['head'].unitsPerEm
    scale = spec['scale']
    sx, sy = spec['widthScale'] * scale, scale
    if role == 'suffix':
        cursor += PARAMS['suffixGapEm'] * units
    for index, character in enumerate(spec['text']):
        name = cmap[ord(character)]
        transform = (sx, 0, 0, -sy, cursor, 0)
        pen = SVGPathPen(glyphs, ntos=lambda n: f'{n:.3f}'.rstrip('0').rstrip('.') if n else '0')
        glyphs[name].draw(TransformPen(pen, transform))
        box = BoundsPen(glyphs)
        glyphs[name].draw(TransformPen(box, transform))
        bounds.append(box.bounds)
        paths.append((f'{role}-{index}-{character}', pen.getCommands()))
        advance = glyphs[name].width
        if index + 1 < len(spec['text']):
            right = cmap[ord(spec['text'][index + 1])]
            advance += pair_spacing(font, name, right)
            advance += units * spec['trackingEm']
            advance += units * spec.get('opticalPairsEm', {}).get(character + spec['text'][index + 1], 0)
        cursor += advance * sx

margin = 20
left = min(b[0] for b in bounds) - margin
top = min(b[1] for b in bounds) - margin
width = max(b[2] for b in bounds) - left + margin
height = max(b[3] for b in bounds) - top + margin
viewbox = ' '.join(f'{n:.3f}' for n in [left, top, width, height])
svg_paths = '\n'.join(f'  <path id="{key}" d="{d}"/>' for key, d in paths)
svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="{viewbox}" fill="currentColor" role="img" aria-labelledby="wordmark-title">
  <title id="wordmark-title">ManSeekSong OS</title>
  <desc>Inter outlines. Uniform medium strokes and a shared baseline. Individual glyph paths remain editable.</desc>
{svg_paths}
</svg>
'''
(ASSETS / 'manseeksong-os.svg').write_text(svg)
jsx_paths = '\n'.join(f'      <path d="{d}" />' for _, d in paths)
jsx = f'''// Generated by scripts/build-brand-wordmark.py; edit assets/brand/wordmark-design.json.
import {{ BRAND }} from '../domain/brand';

/** Fixed vector geometry keeps the brand independent of device and reading fonts. */
export function BrandWordmark() {{
  return (
    <svg className="brand-mark" viewBox="{viewbox}" fill="currentColor" role="img" aria-label={{BRAND.productName}}>
{jsx_paths}
    </svg>
  );
}}
'''
(ROOT / 'src' / 'ui' / 'brand-wordmark.tsx').write_text(jsx)
print(f'Wordmark: {len(paths)} glyph outlines; aspect ratio {width/height:.3f}')
