import { createRoot } from "react-dom/client";
import App from "./App";
import { NavigationHistoryProvider } from "./ui/navigation-history";
import { ScreenBoundary } from "./ui";
import { BackupRecoveryGate } from "./ui/full-backup";
import "./app.css";
import "./ui/observatory-workspace.css";
import "./ui/observatory-layout.css";
import "./ui/paper-typography.css";
import "./ui/paper-typeface.css";
import "./ui/os-task-surfaces.css";
createRoot(document.getElementById("root")!).render(<NavigationHistoryProvider><ScreenBoundary><BackupRecoveryGate><App /></BackupRecoveryGate></ScreenBoundary></NavigationHistoryProvider>);
