import { createRoot } from "react-dom/client";
import App from "./App";
import { ScreenBoundary } from "./ui";
import { BackupRecoveryGate } from "./ui/full-backup";
import "./app.css";
import "./ui/observatory-workspace.css";
import "./ui/observatory-layout.css";
import "./ui/paper-typography.css";
import "./ui/paper-typeface.css";
createRoot(document.getElementById("root")!).render(<ScreenBoundary><BackupRecoveryGate><App /></BackupRecoveryGate></ScreenBoundary>);
