import { test, expect } from '@playwright/test';
test.skip(!process.env.STUDY_AI_FIXTURE_URL, '격리 합성 GPT 화면 주소가 필요합니다.');
test('카드 편집·제외·새 생성·저장·재접속에서도 답 공개가 해당 카드에만 적용된다', async ({ page }) => {
  const external: string[] = [], errors: string[] = [];
  page.on('request', request => { if (/^https?:/.test(request.url()) && !request.url().startsWith(process.env.STUDY_AI_FIXTURE_URL!)) external.push(request.url()); });
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(process.env.STUDY_AI_FIXTURE_URL! + '#/materials/new');
  await page.getByRole('textbox', { name: '자료 제목', exact: true }).fill('공개 범위 합성 검증');
  await page.getByRole('textbox', { name: '강의 내용·필기', exact: true }).fill('합성 원문과 조건');
  await page.getByRole('combobox', { name: 'GPT 작업', exact: true }).selectOption('questions');
  await page.getByRole('button', { name: '인출 질문 만들기', exact: true }).tap();
  await page.getByRole('button', { name: '플래시카드 2', exact: true }).tap();
  await page.getByRole('button', { name: '카드 수정', exact: true }).tap();
  await expect(page.getByRole('textbox', { name: '카드 답', exact: true })).toHaveValue('합성 첫 숨긴 답');
  await page.getByRole('button', { name: '이 카드 제외', exact: true }).tap();
  await expect(page.getByRole('textbox', { name: '카드 답', exact: true })).toHaveCount(0);
  await expect(page.getByText('합성 둘째 숨긴 답', { exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: '답 보기', exact: true }).tap();
  await expect(page.getByText('합성 둘째 숨긴 답', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: '자료 저장', exact: true }).tap();
  await expect(page.getByText('자료를 서버에 저장했습니다.', { exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByText('합성 둘째 숨긴 답', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: '새 결과 만들기', exact: true }).tap();
  await page.getByRole('button', { name: '플래시카드 2', exact: true }).tap();
  await expect(page.getByRole('textbox', { name: '카드 답', exact: true })).toHaveCount(0);
  await expect(page.getByText('합성 첫 숨긴 답', { exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: '답 보기', exact: true })).toBeVisible();
  expect(external).toEqual([]); expect(errors).toEqual([]);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
});
