import { expect, test } from '@playwright/test';
import { decodeStoredText } from '../../src/data/storage-codec';

test('home tools cross midnight without moving focus or creating study records', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-10-01T14:59:30Z') });
  await page.goto('?space=demo#/');
  const tools = page.getByRole('region', { name: '지금 쓸 수 있는 공부 도구', exact: true });
  await expect(tools.locator('time')).toHaveText('23:59');
  await expect(tools.getByText('2026년 10월 1일 목요일', { exact: true })).toBeVisible();
  const trigger = tools.getByRole('button', { name: '공부 기록하기', exact: true });
  await trigger.focus();
  const before = await page.evaluate(() => localStorage.getItem('study-space:demo:v1'));
  await page.clock.fastForward(31_000);
  await expect(tools.locator('time')).toHaveText('00:00');
  await expect(tools.getByText('2026년 10월 2일 금요일', { exact: true })).toBeVisible();
  await expect(trigger).toBeFocused();
  expect(await page.evaluate(() => localStorage.getItem('study-space:demo:v1'))).toBe(before);
  await expect(tools.locator('[aria-live="off"]')).toHaveCount(1);
});

test('home tools save exact long records and free drafts and reopen them on every width', async ({ page }, info) => {
  const original = `  조건·예외·불확실\n${'원문을 그대로 남기고 전체 글로 돌아갑니다. '.repeat(100)}\n끝 공백  `;
  const draft = '  과목을 고르지 않은 생각\n이해 여부는 미확인  ';
  await page.goto('?space=demo#/');
  const tools = page.getByRole('region', { name: '지금 쓸 수 있는 공부 도구', exact: true });
  await expect(tools.getByRole('button')).toHaveCount(3);
  await tools.getByRole('button', { name: '자유롭게 쓰기', exact: true }).tap();
  const writing = page.getByRole('textbox', { name: '자유 기록', exact: true });
  await writing.fill(draft);
  await page.locator('nav a[href="#/"]').filter({ visible: true }).first().tap();
  await tools.getByRole('button', { name: '공부 기록하기', exact: true }).tap();
  await page.getByRole('checkbox', { name: '함수는 어떤 관계일까?', exact: true }).check();
  await page.getByRole('textbox', { name: '메모', exact: true }).fill(original);
  await page.getByRole('button', { name: '1개 주제 기록 저장', exact: true }).tap();
  await page.locator('nav a[href="#/"]').filter({ visible: true }).first().tap();
  const recent = page.getByRole('region', { name: '최근 남긴 공부 기록', exact: true });
  await expect(recent.locator('.prose')).toHaveText(original);
  const preview = await recent.locator('.prose').evaluate(element => ({ height: element.getBoundingClientRect().height, line: parseFloat(getComputedStyle(element).lineHeight), full: element.scrollHeight }));
  expect(preview.height).toBeLessThanOrEqual(preview.line * 3 + 1);
  expect(preview.full).toBeGreaterThan(preview.height);
  await recent.getByRole('link', { name: '기록 열기', exact: true }).tap();
  await expect(page.locator('.record-card .prose').filter({ hasText: '조건·예외·불확실' }).first()).toHaveText(original);
  await page.reload();
  await expect(page.locator('.record-card .prose').filter({ hasText: '조건·예외·불확실' }).first()).toHaveText(original);
  await page.locator('nav a[href="#/"]').filter({ visible: true }).first().tap();
  await tools.getByRole('button', { name: '자유롭게 쓰기', exact: true }).tap();
  await expect(writing).toHaveValue(draft);
  await page.reload();
  await expect(writing).toHaveValue(draft);
  await page.locator('nav a[href="#/"]').filter({ visible: true }).first().tap();
  await tools.getByRole('button', { name: '주제 카드로 설명하기', exact: true }).tap();
  await expect(page).toHaveURL(/#\/recall$/);
  await expect(page.locator('main h1')).toBeVisible();
  const saved = JSON.parse(decodeStoredText((await page.evaluate(() => localStorage.getItem('study-space:demo:v1')))!)).data;
  expect(saved.records).toHaveLength(1);
  expect(saved.records[0].body).toBe(original);
  await page.locator('nav a[href="#/"]').filter({ visible: true }).first().tap();
  await page.getByRole('combobox', { name: '공부 범위', exact: true }).selectOption('independent');
  await expect(tools.getByRole('button')).toHaveCount(3);
  await expect(recent).toHaveCount(0);
  await page.getByRole('combobox', { name: '공부 범위', exact: true }).selectOption('all');
  await expect(recent.locator('.prose')).toHaveText(original);
  expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1);
  await tools.scrollIntoViewIfNeeded();
  await page.screenshot({ path: info.outputPath('home-tools.png') });
});
