import { expect, test } from '@playwright/test';

test('motion controls, player fallback and reopening preserve an edited record', async ({ page }, info) => {
  await page.goto('?space=demo#/record');
  await page.getByRole('checkbox', { name: '함수는 어떤 관계일까?', exact: true }).check();
  const note = '  움직임 확인용 원문\n조건과 예외를 그대로 보존한다.  ';
  const input = page.getByRole('textbox', { name: '메모', exact: true }).first();
  await input.fill(note);
  const tools = page.locator('.sidebar-bottom:visible, .compact-menu:visible').first();
  await tools.locator('summary').click();
  const launcher = tools.getByRole('button', { name: '움직임 위젯', exact: true });
  await launcher.click();
  const dialog = page.getByRole('dialog', { name: '움직임 위젯', exact: true });
  await expect(dialog).toBeVisible();
  const pause = dialog.getByRole('button', { name: '움직임 일시정지', exact: true });
  await expect(dialog.locator('[data-motion-source="lottiefiles"] canvas')).toBeVisible();
  await pause.click();
  await expect(dialog.getByRole('button', { name: '움직임 재생', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await dialog.getByRole('button', { name: '움직임 재생', exact: true }).click();
  await dialog.getByRole('tab', { name: '인터랙티브 카드', exact: true }).click();
  await expect(dialog.locator('[data-motion-source="rive"] canvas')).toBeVisible();
  await dialog.getByRole('button', { name: '5개', exact: true }).click();
  await dialog.getByRole('checkbox', { name: '움직임 줄이기', exact: true }).check();
  await expect(dialog.getByText('★★★★★', { exact: true })).toBeVisible();
  await expect(dialog.getByRole('button', { name: '5개', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await dialog.getByRole('checkbox', { name: '움직임 줄이기', exact: true }).uncheck();
  await expect(dialog.locator('[data-motion-source="rive"] canvas')).toBeVisible();
  await expect(dialog.getByRole('button', { name: '5개', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await dialog.getByRole('tab', { name: '선형 아이콘', exact: true }).click();
  await expect(dialog.getByRole('button', { name: '아이콘 움직임 다시 보기', exact: true })).toBeEnabled();
  await dialog.getByRole('button', { name: '아이콘 움직임 다시 보기', exact: true }).click();
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await expect(dialog.getByRole('button', { name: '아이콘 움직임 다시 보기', exact: true })).toBeDisabled();
  await expect(dialog.getByRole('checkbox', { name: '움직임 줄이기', exact: true })).not.toBeChecked();
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  await expect(dialog.getByRole('button', { name: '아이콘 움직임 다시 보기', exact: true })).toBeEnabled();
  await dialog.getByRole('checkbox', { name: '움직임 줄이기', exact: true }).check();
  await page.screenshot({ path: info.outputPath('motion-controls.png'), fullPage: true });
  await dialog.getByRole('button', { name: '움직임 위젯 닫기', exact: true }).click();
  await expect(launcher).toBeFocused();
  await expect(input).toHaveValue(note);
  await page.reload();
  await expect(input).toHaveValue(note);
  await tools.locator('summary').click();
  await launcher.click();
  await expect(dialog.getByRole('checkbox', { name: '움직임 줄이기', exact: true })).toBeChecked();
  await expect(dialog.getByRole('button', { name: '움직임 일시정지', exact: true })).toBeDisabled();
  await page.keyboard.press('Escape');
  await expect(dialog).toHaveCount(0);
  await expect(input).toHaveValue(note);
  await page.getByRole('button', { name: '1개 주제 기록 저장', exact: true }).click();
  await expect(page.getByRole('heading', { name: '최근 남긴 기록', exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByText(/움직임 확인용 원문/).first()).toBeVisible();
});
