import {test,expect} from '@playwright/test';
const base='/?space=demo&math=physics#/math';
test('물리 공개본 · 정확값과 미확정 입력·저장 실패·복원·원문 복귀',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.getByRole('button',{name:'등가속도 운동 열기',exact:true}).click();const d=page.locator('.physics-modal'),input=d.getByLabel('가속도 정확한 입력',{exact:true});await input.fill('4');await input.press('Enter');await expect(d.locator('[data-observation-region="readout"]')).toContainText('v=6');await input.fill('2 +');await input.press('Enter');await expect(input).toHaveAttribute('aria-invalid','true');await d.getByLabel('이 기기의 관찰 메모',{exact:true}).fill('공개 흐름의 조건 메모');await d.getByRole('button',{name:'연결된 원문 열기',exact:true}).click();const s=page.locator('.physics-source-modal');await expect(s.getByLabel('물리 원본 PDF 연결 · 이 기기에 보관',{exact:true})).toBeVisible();await s.getByLabel('물리 원본 PDF 연결 · 이 기기에 보관',{exact:true}).setInputFiles({name:'wrong.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.7 synthetic')});await expect(s.getByRole('alert')).toContainText('같은 판본');await s.getByRole('button',{name:'읽던 관찰로 돌아가기',exact:true}).click();await expect(input).toHaveValue('2 +');await expect(d.getByRole('button',{name:'연결된 원문 열기',exact:true})).toBeFocused();await page.reload();await page.getByRole('button',{name:'등가속도 운동 열기',exact:true}).click();await expect(page.locator('.physics-modal').getByLabel('가속도 정확한 입력',{exact:true})).toHaveValue('2 +');await expect(page.locator('.physics-modal').getByLabel('이 기기의 관찰 메모',{exact:true})).toHaveValue('공개 흐름의 조건 메모');
 await page.evaluate(()=>{const original=Storage.prototype.setItem;(window as any).__physicsRestore=()=>{Storage.prototype.setItem=original;};Storage.prototype.setItem=function(k:string,v:string){if(k.includes(':physics-observations:'))throw new DOMException('synthetic','QuotaExceededError');return original.call(this,k,v);};});await page.locator('.physics-modal').getByLabel('이 기기의 관찰 메모',{exact:true}).fill('실패 중에도 입력 보존');await expect(page.locator('.physics-modal').getByRole('alert')).toBeVisible();await page.evaluate(()=>(window as any).__physicsRestore());await page.locator('.physics-modal').getByRole('button',{name:'보관 다시 시도',exact:true}).click();await page.reload();await page.getByRole('button',{name:'등가속도 운동 열기',exact:true}).click();await expect(page.locator('.physics-modal').getByLabel('이 기기의 관찰 메모',{exact:true})).toHaveValue('실패 중에도 입력 보존');expect(errors).toEqual([]);
});
test('물리 공개본 · 자료와 작업대 사이의 값·호출자·초점 보존',async({page})=>{
 await page.goto('/?space=demo#/materials/physics-principles');await page.getByRole('button',{name:'등가속도 운동 열기',exact:true}).click();const d=page.locator('.physics-modal');await d.getByLabel('가속도 정확한 입력',{exact:true}).fill('3');await d.getByLabel('가속도 정확한 입력',{exact:true}).press('Enter');await d.getByRole('button',{name:'탐구 작업대에서 전체 관찰 열기',exact:true}).click();await expect(page).toHaveURL(/#\/math$/);await expect(page.locator('.physics-modal').getByLabel('가속도 정확한 입력',{exact:true})).toHaveValue('3');await page.locator('.physics-modal').getByRole('button',{name:'읽던 절로 돌아가기',exact:true}).click();await expect(page).toHaveURL(/#\/materials\/physics-principles$/);await expect(page.locator('#physics-section-3\\.5 button').first()).toBeFocused();
});
test('물리 공개본 · 28장 목록과 한국어 조건·원식·책/PDF 구별',async({page})=>{
 await page.goto(base);await expect(page.getByLabel('교재의 장').locator('option')).toHaveCount(28);await page.goto('/?space=demo&math=physics&physicsSection=23.3#/math');const r=page.locator('.physics-reading-modal');await r.locator('.physics-verified-links summary').click();await expect(r).toContainText('유전체');await expect(r).toContainText('책 시작');await expect(r).toContainText('PDF');await expect(r.locator('.katex-error')).toHaveCount(0);expect(await r.evaluate(el=>el.scrollWidth<=el.clientWidth+2)).toBe(true);await expect(r.getByLabel('물리 원본 PDF 연결 · 이 기기에 보관',{exact:true})).toBeVisible();
});
test('물리 공개본 · 세기 아래첨자와 그래프 기호·적용 조건',async({page})=>{
 for(const id of ['c15-sound','c18-slits','c18-thin-film']){await page.goto(`/?space=demo&math=physics&physics=${id}#/math`);const d=page.locator('.physics-modal');await expect(d.locator('.physics-plot .main-svg').first()).toBeVisible();await expect(d.locator('.katex-error')).toHaveCount(0);const c=d.locator('[data-observation-region="question"] > .physics-prose');expect(await c.innerText()).not.toContain('I_');expect(await c.locator('.katex').count()).toBeGreaterThan(0);expect(await d.evaluate(el=>el.scrollWidth<=el.clientWidth+2)).toBe(true);}
});
test('물리 원본 · 기기 PDF 연결과 확대·재접속 보관',async({page},info)=>{
 test.skip(!process.env.PHYSICS_TEST_PDF||info.project.name!=='iPad-Pro-13-half-window','실제 교재 파일은 로컬 지정시에만 확인하며 CI에 원본을 올리지 않는다.');
 test.setTimeout(120000);await page.goto('/?space=demo&math=physics&physicsSection=23.3#/math');const r=page.locator('.physics-reading-modal');await r.getByRole('button',{name:'원본 그림·수식 펼치기',exact:true}).click();await r.getByLabel('물리 원본 PDF 연결 · 이 기기에 보관',{exact:true}).setInputFiles(process.env.PHYSICS_TEST_PDF!);await expect(r.locator('canvas')).toBeVisible({timeout:60000});await expect.poll(()=>r.locator('canvas').evaluate(c=>(c as HTMLCanvasElement).width),{timeout:60000}).toBeGreaterThan(300);const width=await r.locator('canvas').evaluate(c=>(c as HTMLCanvasElement).width);await r.getByRole('button',{name:'원본 확대',exact:true}).click();await expect.poll(()=>r.locator('canvas').evaluate(c=>(c as HTMLCanvasElement).width)).toBeGreaterThan(width);await r.getByLabel('물리 원본 PDF 연결 · 이 기기에 보관',{exact:true}).setInputFiles({name:'wrong.pdf',mimeType:'application/pdf',buffer:Buffer.from('wrong')});await expect(r.getByRole('alert')).toContainText('같은 판본');await expect(r.locator('canvas')).toBeVisible();const saved=await r.locator('canvas').evaluate(c=>(c as HTMLCanvasElement).width);await page.reload();await expect(page.locator('.physics-reading-modal canvas')).toBeVisible({timeout:60000});await expect.poll(()=>page.locator('.physics-reading-modal canvas').evaluate(c=>(c as HTMLCanvasElement).width)).toBe(saved);await expect(page.locator('.physics-reading-modal .katex-error')).toHaveCount(0);await page.locator('.physics-reading-modal').getByRole('button',{name:'본문 추출본 읽기',exact:true}).click();await expect(page.locator('.physics-reading-modal .physics-device-source pre')).toContainText('dielectric',{ignoreCase:true});
});
