import { expect, test } from '@playwright/test';
import { createDemoState } from '../../src/domain/fixtures';
import { decodeStoredText, encodeStoredText } from '../../src/data/storage-codec';

test('switches past a long first course, keeps both drafts on reload and saves one study session', async ({ page }, info) => {
  const data = createDemoState();
  const first = data.nodes.find(node => node.id === 'demo-topic-function')!;
  for (let index = 0; index < 90; index++) data.nodes.push({ ...first, id: `long-topic-${index}`, name: `긴 첫 과목 주제 ${index}`, order: index + 2 });
  const raw = encodeStoredText(JSON.stringify({ sequence: 0, data }));
  await page.addInitScript(value => {
    if (!localStorage.getItem('study-space:demo:v1')) localStorage.setItem('study-space:demo:v1', value);
  }, raw);
  await page.goto('?space=demo#/record');
  const course = page.getByRole('combobox', { name: '기록할 과목', exact: true });
  await expect(course).toHaveValue('all');
  await expect(course.getByRole('option', { name: '수학의 기초 · 92개 주제', exact: true })).toHaveCount(1);
  await expect(course.getByRole('option', { name: '과학 탐구 · 1개 주제', exact: true })).toHaveCount(1);
  await page.getByRole('checkbox', { name: first.name, exact: true }).check();
  const original = '  첫 과목 원문\n조건과 예외  ';
  await page.getByRole('textbox', { name: '메모', exact: true }).fill(original);
  await page.getByRole('checkbox', { name: '긴 첫 과목 주제 80', exact: true }).scrollIntoViewIfNeeded();
  // On short screens the controls scroll normally so they cannot cover the rows.
  if (page.viewportSize()!.height <= 512) await course.scrollIntoViewIfNeeded();
  const courseBox = await course.boundingBox();
  const navBox = await page.locator('.navigation-history-bar').boundingBox();
  expect(courseBox!.y).toBeGreaterThanOrEqual(navBox!.y + navBox!.height - 1);
  expect(courseBox!.y + courseBox!.height).toBeLessThanOrEqual(page.viewportSize()!.height);
  await course.selectOption('demo-subject-science');
  await expect(page.getByRole('checkbox', { name: first.name, exact: true })).toHaveCount(0);
  await page.getByRole('checkbox', { name: '힘과 움직임', exact: true }).check();
  await page.getByRole('textbox', { name: '메모', exact: true }).nth(1).fill('두 번째 과목 원문');
  await page.reload();
  await expect(course).toHaveValue('demo-subject-science');
  await expect(page.getByRole('textbox', { name: '메모', exact: true }).nth(0)).toHaveValue(original);
  await expect(page.getByRole('textbox', { name: '메모', exact: true }).nth(1)).toHaveValue('두 번째 과목 원문');
  await course.selectOption('demo-subject-independent');
  await expect(page.getByRole('link', { name: '과목에서 주제 추가', exact: true })).toBeVisible();
  await course.selectOption('all');
  await page.getByRole('searchbox', { name: '주제 찾기', exact: true }).fill('과학 탐구');
  await expect(page.getByRole('checkbox', { name: '힘과 움직임', exact: true })).toBeChecked();
  await expect(page.getByRole('checkbox', { name: first.name, exact: true })).toHaveCount(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  await page.screenshot({ path: info.outputPath('record-course-picker.png') });
  await page.getByRole('button', { name: '2개 주제 기록 저장', exact: true }).click();
  await expect(page.locator('main h1').first()).not.toHaveText('공부 기록');
  const persisted = await page.evaluate(() => localStorage.getItem('study-space:demo:v1'));
  const saved = JSON.parse(decodeStoredText(persisted!)).data;
  expect(saved.records).toHaveLength(2);
  expect(saved.records.map((record: { subjectId: string }) => record.subjectId)).toEqual(['demo-subject-math', 'demo-subject-science']);
  expect(saved.records.map((record: { body: string }) => record.body)).toEqual([original, '두 번째 과목 원문']);
  expect(saved.sessions).toHaveLength(1);
});
