/** Textbook-scoped models. No UI, storage, server SDK or executable content data. */
export type Field = { key: string; label: string; unit: string; min: number; max: number; value: number; step: number };
export type Model = { id: string; sections: string[]; title: string; question: string; tex: string; fields: Field[]; result: string; unit: string; conditions: string; limit: string; reason: string; steps?: string[] };
const f = (key: string, label: string, unit: string, min: number, max: number, value: number, step = 0.1): Field => ({ key, label, unit, min, max, value, step });
export const MODELS: Model[] = [
 {id:'mole',sections:['3.1','3.2','3.7'],title:'질량과 몰',question:'같은 질량도 몰질량이 다르면 입자 수가 어떻게 달라지는가?',tex:'n=m/M',fields:[f('m','질량 m','g',0,1000,18),f('M','몰질량 M','g mol⁻¹',0.001,1000,18)],result:'물질량 n',unit:'mol',conditions:'시료의 순도와 화학식이 확인된 하나의 물질.',limit:'몰질량을 입력한다. 화학식 자동 해석·순도 보정은 하지 않는다.',reason:'18 g과 18 g mol⁻¹은 질량에서 1 mol로 환산하는 관계가 보이는 설명용 초기값이다.'},
 {id:'isotope',sections:['2.3','2.4'],title:'동위원소 평균 질량',question:'두 동위원소의 존재비가 평균 질량에 어떻게 반영되는가?',tex:'\\bar m=xm_1+(1-x)m_2',fields:[f('m1','첫 동위원소 질량 m₁','u',0.001,300,35),f('m2','둘째 동위원소 질량 m₂','u',0.001,300,37),f('x','첫 동위원소 존재비 x','1',0,1,0.75,0.01)],result:'평균 질량',unit:'u',conditions:'동위원소가 둘뿐인 설명 모형. 존재비 합은 1.',limit:'35와 37은 설명용 질량이며 실제 염소의 정밀 질량·존재비가 아니다.',reason:'두 끝값 사이의 가중 평균이 보이게 한다.'},
 {id:'dilution',sections:['4.7','4.8'],title:'희석과 용질량',question:'용질량이 보존되면 부피와 농도는 어떻게 대응하는가?',tex:'c_1V_1=c_2V_2',fields:[f('c1','처음 농도 c₁','mol L⁻¹',0,10,1),f('v1','처음 부피 V₁','mL',0.1,2000,100),f('v2','최종 부피 V₂','mL',0.1,2000,200)],result:'최종 농도 c₂',unit:'mol L⁻¹',conditions:'용질의 반응·손실이 없고 최종 용액 부피를 안다.',limit:'부피를 더하면 언제나 최종 부피가 된다는 가정은 하지 않는다.',reason:'부피가 2배이면 농도가 절반이 되는 초기값.'},
 {id:'gas',sections:['5.2','5.3'],title:'이상기체 상태',question:'같은 몰수에서 온도와 압력은 부피를 어떻게 바꾸는가?',tex:'V=\\frac{nRT}{P}',fields:[f('n','물질량 n','mol',0.001,10,1),f('T','절대온도 T','K',1,1000,300,1),f('P','압력 P','atm',0.001,20,1)],result:'부피 V',unit:'L',conditions:'이상기체 모형. 압력은 절대압력, 온도는 K.',limit:'실제 기체의 고압·저온 오차를 이 식으로 추정하지 않는다. R=0.082057 L atm mol⁻¹ K⁻¹.',reason:'1 mol, 300 K, 1 atm에서 P와 T의 비례·반비례가 보인다.'},
 {id:'dalton',sections:['5.5'],title:'분압의 합',question:'혼합기체의 각 성분 압력은 전체 압력에 어떻게 기여하는가?',tex:'P=P_A+P_B,\\quad y_A=P_A/P',fields:[f('a','성분 A 분압 P_A','atm',0,10,0.6),f('b','성분 B 분압 P_B','atm',0,10,0.4)],result:'전체 압력',unit:'atm',conditions:'이상기체 혼합물, 같은 용기·온도. 둘의 합은 양수.',limit:'증기·건조기체 구별과 물의 증기압 자료는 별도로 필요하다.',reason:'합이 1 atm인 두 성분으로 합과 비율을 읽는다.'},
 {id:'graham',sections:['5.7'],title:'분출 속도의 비',question:'같은 온도에서 몰질량은 분출 속도의 비에 어떻게 작용하는가?',tex:'r_A/r_B=\\sqrt{M_B/M_A}',fields:[f('a','기체 A 몰질량','g mol⁻¹',0.001,300,4),f('b','기체 B 몰질량','g mol⁻¹',0.001,300,16)],result:'분출 속도비 r_A/r_B',unit:'1',conditions:'같은 온도와 비교 가능한 분출 조건.',limit:'일반 유동 속도나 모든 확산 과정을 이 비로 대신하지 않는다.',reason:'몰질량 비 4에서 속도비 2를 확인한다.'},
 {id:'heat',sections:['6.6'],title:'열량계의 열',question:'질량·비열·온도 변화가 흡수한 열에 어떻게 연결되는가?',tex:'q=mc\\Delta T',fields:[f('m','질량 m','g',0.001,2000,100),f('c','비열 c','J g⁻¹ K⁻¹',0.001,10,4.184,0.001),f('dt','온도 변화 ΔT','K',-100,100,10)],result:'열 q',unit:'J',conditions:'선택한 시료의 c를 상수로 근사하며 상전이 없음.',limit:'반응열을 구하려면 용기 열용량·열손실·계의 부호를 추가해야 한다.',reason:'100 g 물에 가까운 시료의 10 K 변화로 열의 부호와 크기를 읽는다.'},
 {id:'photon',sections:['7.1','7.2'],title:'파장과 광자 에너지',question:'파장이 짧아지면 진동수와 광자 에너지는 어떻게 변하는가?',tex:'\\nu=c/\\lambda,\\quad E=h\\nu',fields:[f('lambda','진공 파장 λ','nm',1,2000,500,1)],result:'광자 에너지 E',unit:'J',conditions:'진공 파장·한 광자. h=6.62607015×10⁻³⁴ J s, c=299792458 m s⁻¹.',limit:'상수의 정확값은 현재 SI 보충이다. 교재의 반올림 상수와 구별한다.',reason:'가시광선 범위의 500 nm가 비교의 출발점이다.'},
 {id:'colligative',sections:['12.6','12.8'],title:'어는점 내림',question:'용질 입자량과 용매의 상수가 어는점 변화에 어떻게 연결되는가?',tex:'\\Delta T_f=iK_fm',fields:[f('i','van’t Hoff 인자 i','1',0.1,5,1),f('kf','용매 어는점 내림 상수 K_f','K kg mol⁻¹',0.001,30,1.86),f('m','몰랄농도 m','mol kg⁻¹',0,2,0.1,0.01)],result:'어는점 내림 ΔT_f',unit:'K',conditions:'묽은 이상 용액 근사와 해당 용매의 K_f. i는 유효값.',limit:'완전 해리·이온쌍·비이상성으로부터 i를 자동 결정하지 않는다.',reason:'물에 대한 묽은 비전해질 모형으로 시작한다.'},
 {id:'osmosis',sections:['12.7'],title:'삼투압',question:'희석된 용액의 농도와 온도가 삼투압에 어떻게 반영되는가?',tex:'\\Pi=cRT',fields:[f('c','입자 몰농도 c','mol L⁻¹',0,1,0.01,0.001),f('T','절대온도 T','K',1,500,298,1)],result:'삼투압 Π',unit:'atm',conditions:'묽은 이상 용액, 선택적으로 용매가 통과하는 막.',limit:'전해질은 입자 농도를 별도로 반영해야 한다.',reason:'묽은 용액과 실온에 가까운 비교 초기값.'},
 {id:'first-order',sections:['13.4','20.4'],title:'일차 감소',question:'일차 속도 모형에서 시간과 남은 비율·반감기는 어떻게 대응하는가?',tex:'A/A_0=e^{-kt},\\quad t_{1/2}=\\ln 2/k',fields:[f('k','속도 상수 k','s⁻¹',0.000001,1,0.01,0.001),f('t','시간 t','s',0,1000,100,1)],result:'남은 비율 A/A₀',unit:'1',conditions:'단일 일차 반응 또는 단일 핵종 붕괴. k는 시간 동안 일정.',limit:'화학 반응과 핵붕괴는 같은 수학식에 대응하지만 과정의 원인은 다르다.',reason:'kt=1에서 e⁻¹의 감소를 볼 수 있다.'},
 {id:'second-order',sections:['13.4'],title:'이차 반감기',question:'단일 반응물 이차 속도식에서 초기 농도가 반감기를 어떻게 바꾸는가?',tex:'t_{1/2}=1/(k[A]_0)',fields:[f('k','속도 상수 k','L mol⁻¹ s⁻¹',0.000001,10,0.1),f('a','초기 농도 [A]₀','mol L⁻¹',0.000001,10,1)],result:'반감기',unit:'s',conditions:'속도식 −d[A]/dt=k[A]²인 경우.',limit:'교재의 반감기 증가 설명과 반대인 한 문장은 정정 기록과 분리한다.',reason:'초기 농도가 절반이면 반감기가 2배임을 비교한다.'},
 {id:'arrhenius',sections:['13.6','13.9'],title:'온도와 속도상수의 비',question:'활성화에너지와 온도 변화가 속도상수 비에 어떻게 작용하는가?',tex:'\\ln(k_2/k_1)=\\frac{E_a}{R}(1/T_1-1/T_2)',fields:[f('ea','활성화에너지 E_a','kJ mol⁻¹',0,200,50,1),f('t1','처음 절대온도 T₁','K',200,500,298,1),f('t2','둘째 절대온도 T₂','K',200,500,310,1)],result:'속도상수비 k₂/k₁',unit:'1',conditions:'해당 온도 범위에서 E_a와 빈도인자가 일정한 Arrhenius 근사.',limit:'촉매가 평형상수 K를 바꾼다는 뜻이 아니다. R=8.314462618 J mol⁻¹ K⁻¹.',reason:'같은 메커니즘의 작은 온도 변화를 출발점으로 한다.'},
 {id:'equilibrium',sections:['14.2','14.4','14.5'],title:'Q와 K의 비교',question:'같은 온도의 Q와 K를 비교하면 어느 반응 방향이 유리한가?',tex:'\\Delta_rG=RT\\ln(Q/K)',fields:[f('q','반응지수 Q','1',0.000001,100,0.5),f('k','평형상수 K','1',0.000001,100,1)],result:'ln(Q/K)',unit:'1',conditions:'반응식·활동도 기준과 온도가 같은 Q와 K. 양의 무차원값.',limit:'임의 반응의 평형 농도는 자동으로 풀지 않는다. 순수 고체·액체 활동도는 관행에 따라 1이다.',reason:'Q<K, Q=K, Q>K를 비교하기 쉬운 값.'},
 {id:'ph',sections:['15.6','15.8'],title:'pH와 수소 이온',question:'양의 수소 이온 농도와 로그 척도는 어떻게 대응하는가?',tex:'\\mathrm{pH}\\approx-\\log_{10}([H^+]/c^\\circ)',fields:[f('h','수소 이온 농도 [H⁺]','mol L⁻¹',0.0000000000000001,10,0.0000001,0.0000001)],result:'pH 근사',unit:'1',conditions:'활동도를 농도로 근사할 수 있는 묽은 용액, c°=1 mol L⁻¹.',limit:'중성 pH=7은 25 °C에서의 근사이다. 항상 0–14라는 경계로 자르지 않는다.',reason:'25 °C 중성에 가까운 10⁻⁷ mol L⁻¹로 로그를 읽는다.'},
 {id:'weak-acid',sections:['16.1'],title:'약산의 해리량',question:'단일 약산의 물질수지와 해리 평형을 함께 적용하면 무엇이 남는가?',tex:'k_a=K_a c^\\circ,\\quad x=\\frac{2k_a C}{\\sqrt{k_a^2+4k_aC}+k_a}',fields:[f('ka','해리 상수 K_a','1',0.0000000001,1,0.000018,0.000001),f('c','분석 농도 C','mol L⁻¹',0.000001,1,0.1,0.001)],result:'해리량 x ≈ [H⁺]',unit:'mol L⁻¹',conditions:'25 °C의 단일 약산만 있음·활동도≈농도·물의 자동 이온화 무시. c°=1 mol L⁻¹이며 농도식에는 k_a=K_a c°를 사용한다.',limit:'계산된 x가 10⁻⁶ mol L⁻¹ 이하이면 물 기여를 무시한 pH 결과는 보류한다. 다산·염·강산 혼합은 지원하지 않는다.',reason:'0.1 mol L⁻¹의 아세트산에 가까운 설명 모형.'},
 {id:'buffer',sections:['16.5','16.6'],title:'완충용액의 잔여량',question:'강산을 넣은 뒤에도 짝산·짝염기가 모두 남아 비율을 사용할 수 있는가?',tex:'\\mathrm{pH}\\approx\\mathrm{p}K_a+\\log_{10}(n_{A^-}/n_{HA})',fields:[f('ha','처음 짝산 n_HA','mmol',0.001,100,20,1),f('a','처음 짝염기 n_A⁻','mmol',0.001,100,20,1),f('acid','첨가 강산량 (음수는 강염기)','mmol',-100,100,5,1),f('pka','pK_a','1',0,14,4.74,0.01)],result:'pH 근사',unit:'1',conditions:'중화가 먼저 일어나고 짝산·짝염기가 모두 남음. 같은 최종 부피·활동도 근사.',limit:'완충 성분이 소모되면 이 식의 적용을 보류한다. 용액 자체가 불가능하거나 pH가 없다는 뜻은 아니다.',reason:'같은 초기 양에 작은 강산량을 넣어 양론→잔여량→평형 순서를 볼 수 있다.',steps:['강산은 짝염기를, 강염기는 짝산을 중화한다.','중화 뒤 짝산·짝염기가 둘 다 남는지 확인한다.','둘 다 남으면 잔여량의 비를 Henderson–Hasselbalch 식에 사용한다.']},
 {id:'solubility',sections:['17.1','17.2','17.3'],title:'AB형 염의 용해도',question:'공통 이온이 있으면 AB형 염의 평형 용해도는 어떻게 달라지는가?',tex:'K_{sp}=\\frac{s(s+c)}{(c^\\circ)^2},\\quad s=\\frac{2K_{sp}(c^\\circ)^2}{\\sqrt{c^2+4K_{sp}(c^\\circ)^2}+c}',fields:[f('ksp','용해도곱 K_sp','1',0.000000000001,1,0.00000001,0.000000001),f('c','처음 공통 이온 농도 c','mol L⁻¹',0,1,0.001,0.001)],result:'몰 용해도 s',unit:'mol L⁻¹',conditions:'AB형 1:1 염·활동도≈농도·추가 산염기나 착물 반응 없음. c°=1 mol L⁻¹로 농도를 정규화해 무차원 K_sp와 대응한다.',limit:'다른 화학양론·pH 결합·착이온은 별도 평형계가 필요하다.',reason:'작은 K_sp와 양의 공통 이온 농도로 억제 효과를 읽는다.'},
 {id:'gibbs',sections:['18.2','18.4'],title:'엔탈피·엔트로피와 방향',question:'같은 온도에서 엔탈피와 엔트로피 항의 경쟁은 ΔG를 어떻게 바꾸는가?',tex:'\\Delta G=\\Delta H-T\\Delta S',fields:[f('h','엔탈피 변화 ΔH','kJ mol⁻¹',-200,200,40,1),f('s','엔트로피 변화 ΔS','J mol⁻¹ K⁻¹',-500,500,150,1),f('T','절대온도 T','K',1,1000,298,1)],result:'자유에너지 변화 ΔG',unit:'kJ mol⁻¹',conditions:'같은 상태·일정 T,P. 입력값의 온도 의존성을 무시할 수 있는 범위.',limit:'음의 ΔG는 속도가 빠르다는 뜻이 아니다. 표준량 ΔG°와 실제 ΔG를 구별한다.',reason:'상온 부근에서 두 항이 경쟁하는 부호를 비교한다.'},
 {id:'gibbs-k',sections:['18.6','18.7'],title:'표준 자유에너지와 K',question:'ΔG°의 부호와 크기는 평형상수의 로그에 어떻게 대응하는가?',tex:'\\ln K=-\\Delta G^\\circ/(RT)',fields:[f('g','표준 자유에너지 ΔG°','kJ mol⁻¹',-100,100,-10,1),f('T','절대온도 T','K',1,1000,298,1)],result:'ln K',unit:'1',conditions:'같은 T의 ΔG°와 무차원 활동도 기반 K.',limit:'평형에서 ΔG=0이나 ΔG°는 일반적으로 0이 아니다. 교재의 ln K 부호 오류는 별도 기록.',reason:'음의 표준 자유에너지에서 K>1임을 비교한다.'},
 {id:'nernst',sections:['19.4','19.6','19.7'],title:'Nernst 전위',question:'반응지수와 전자 수는 같은 전지의 전위에 어떻게 반영되는가?',tex:'E=E^\\circ-\\frac{RT}{nF}\\ln Q',fields:[f('e','표준 전지 전위 E°','V',-3,3,1.1,0.01),f('T','절대온도 T','K',1,1000,298,1),f('n','반응식의 전자 수 n','1',1,12,2,1),f('q','반응지수 Q','1',0.000001,100,1)],result:'전지 전위 E',unit:'V',conditions:'같은 균형 반응식·무차원 활동도 Q·가역 전지. n은 양의 정수.',limit:'실제 부하 전압·과전압·내부저항을 계산하지 않는다. F=96485.33212 C mol⁻¹.',reason:'표준 상태 Q=1에서 E=E°인 초기값.'},
 {id:'electrolysis',sections:['19.11'],title:'전하량과 석출 질량',question:'전류와 시간이 전자 몰수와 석출 질량에 어떻게 대응하는가?',tex:'m=\\frac{ItM}{nF}',fields:[f('i','전류 I','A',0,100,1),f('t','시간 t','s',0,100000,3600,1),f('M','생성물 몰질량 M','g mol⁻¹',0.001,300,63.55),f('n','생성물당 전자 수 n','1',1,12,2,1)],result:'석출 질량 m',unit:'g',conditions:'반응식 확인·전류 일정·전류 효율 100%인 모형·n 정수.',limit:'경쟁 반응·전류 효율·전극 반응 선택은 자동 결정하지 않는다.',reason:'1 A를 1시간 가하는 구리 석출 모형.'},
];
export const INITIAL_REASON = '초기값은 설명용 비교 상태이며 사용자 자료나 측정 결과가 아니다.';
export const modelById = (id: string) => MODELS.find(m => m.id === id);
export const modelsForSection = (section: string) => MODELS.filter(m => m.sections.includes(section));
export const defaults = (m: Model) => Object.fromEntries(m.fields.map(f => [f.key, f.value]));
export type Judgment = { value: number | null; detail: string; state: 'fulfilled' | 'violated' | 'unknown' };
export function calculate(m: Model, v: Record<string, number>, condition: Judgment['state']): Judgment {
 if (condition !== 'fulfilled') return {value:null,state:condition,detail:condition==='unknown'?'적용 조건을 아직 확인하지 않았다. 판단을 보류한다.':'이 모형의 적용 조건을 충족하지 않는다. 대상 자체의 불가능·거짓을 뜻하지 않는다.'};
 if (m.fields.some(f => !Number.isFinite(v[f.key]) || v[f.key] < f.min || v[f.key] > f.max) || (['nernst','electrolysis'].includes(m.id) && !Number.isInteger(v.n))) return {value:null,state:'violated',detail:'입력 범위·단위 또는 정수 조건을 확인해야 한다.'};
 const R=8.314462618, F=96485.33212; let value=NaN,detail='입력과 수식의 같은 변수를 사용한 모형 계산이다.';
 switch(m.id) {
 case 'mole': value=v.m/v.M; break;
 case 'isotope': value=v.x*v.m1+(1-v.x)*v.m2; break;
 case 'dilution': value=v.c1*v.v1/v.v2; if(v.v2<v.v1)detail='부피 감소 상태이다. 용질량 보존식은 계산했지만 희석이라는 명칭에는 해당하지 않는다.'; break;
 case 'gas': value=v.n*0.082057*v.T/v.P; break;
 case 'dalton': value=v.a+v.b; if(value===0)return {value:null,state:'violated',detail:'성분 합이 0이라 몰분율을 판단하지 않는다.'}; detail=`A의 몰분율 = ${v.a/value}. 전체 압력은 분압의 합이다.`;break;
 case 'graham': value=Math.sqrt(v.b/v.a); break;
 case 'heat': value=v.m*v.c*v.dt; break;
 case 'photon': value=6.62607015e-34*299792458/(v.lambda*1e-9);detail=`진동수 = ${299792458/(v.lambda*1e-9)} Hz. 파장 단위 nm를 m로 환산했다.`;break;
 case 'colligative': value=v.i*v.kf*v.m;break;
 case 'osmosis': value=v.c*0.082057*v.T;break;
 case 'first-order': value=Math.exp(-v.k*v.t);detail=`반감기 = ${Math.log(2)/v.k} s. 남은 비율과 반감기는 같은 k에 대응한다.`;break;
 case 'second-order': value=1/(v.k*v.a);break;
 case 'arrhenius': value=Math.exp(v.ea*1000/R*(1/v.t1-1/v.t2));break;
 case 'equilibrium': value=Math.log(v.q/v.k);detail=v.q<v.k?'Q<K: 정반응 방향이 유리하다.':v.q>v.k?'Q>K: 역반응 방향이 유리하다.':'Q=K: 해당 온도의 평형 조건이다.';break;
 case 'ph': value=-Math.log10(v.h);break;
 case 'weak-acid': {const x=2*v.ka*v.c/(Math.sqrt(v.ka*v.ka+4*v.ka*v.c)+v.ka);value=x;if(x<=1e-6)return {value:null,state:'unknown',detail:'물의 자동 이온화를 무시할 수 있는지 확인해야 한다. 이 모형의 pH 판단을 보류한다.'};detail=`pH 근사 = ${-Math.log10(x)}. x/C = ${x/v.c}; 작은 x 근사를 쓰지 않고 이차식을 계산했다.`;break;}
 case 'buffer': {const a=v.a-v.acid, ha=v.ha+v.acid;if(a<=0||ha<=0)return {value:null,state:'violated',detail:`중화 뒤 A⁻=${a} mmol, HA=${ha} mmol. 두 성분이 모두 남지 않아 이 비율식을 사용하지 않는다. 잉여 강산·강염기를 포함한 별도 평형 계산이 필요하다.`}; value=v.pka+Math.log10(a/ha);detail=`중화 뒤 A⁻=${a} mmol, HA=${ha} mmol. 같은 최종 부피에서 농도비는 양의 잔여 몰수비에 대응한다.`;break;}
 case 'solubility': value=2*v.ksp/(Math.sqrt(v.c*v.c+4*v.ksp)+v.c);break;
 case 'gibbs': value=v.h-v.T*v.s/1000;detail=value<0?'ΔG<0: 주어진 T,P와 상태에서 정방향 변화가 열역학적으로 유리하다.':value>0?'ΔG>0: 같은 조건에서 역방향이 유리하다.':'ΔG=0: 해당 조건의 평형.';break;
 case 'gibbs-k': value=-v.g*1000/(R*v.T);break;
 case 'nernst': value=v.e-R*v.T/(v.n*F)*Math.log(v.q);break;
 case 'electrolysis': value=v.i*v.t*v.M/(v.n*F);break;
 }
 return Number.isFinite(value)?{value,state:'fulfilled',detail}:{value:null,state:'unknown',detail:'현재 범위에서 유한한 결과를 얻지 못했다. 계산 범위·입력을 확인해야 한다.'};
}
